/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfaces;

/**
 *
 * @author jheremyPonte
 */
public class asignar_tutor_directivo_1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form asignar_tutor_directivo_1
     */
    public asignar_tutor_directivo_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ckb_AsignarTutor_TresAñitos = new javax.swing.JCheckBox();
        ckb_AsignarTutor_CuatroAñitos = new javax.swing.JCheckBox();
        ckb_AsignarTutor_CincoAñitos = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ckb_AsignarTutor_UnoPrimaria = new javax.swing.JCheckBox();
        ckb_AsignarTutor_DosPrimaria = new javax.swing.JCheckBox();
        ckb_AsignarTutor_TresPrimaria = new javax.swing.JCheckBox();
        ckb_AsignarTutor_CuatroPrimaria = new javax.swing.JCheckBox();
        ckb_AsignarTutor_CincoPrimaria = new javax.swing.JCheckBox();
        ckb_AsignarTutor_SeisPrimaria = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        ckb_AsignarTutor_UnoSecundaria = new javax.swing.JCheckBox();
        ckb_AsignarTutor_DosSecundaria = new javax.swing.JCheckBox();
        ckb_AsignarTutor_TresSecundaria = new javax.swing.JCheckBox();
        ckb_AsignarTutor_CuatroSecundaria = new javax.swing.JCheckBox();
        ckb_AsignarTutor_CincoSecundaria = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_AsignarTutor_registro = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_AsignarTutor_año = new javax.swing.JTextField();
        btn_AsignarTutor_borrar = new javax.swing.JButton();
        cbx_AsignarTutor_Tutor1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btn_AsignarTutor_actualizar = new javax.swing.JButton();
        btn_AsignarTutor_crear = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Inicial:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 37, -1));

        ckb_AsignarTutor_TresAñitos.setText("3 Añitos");
        ckb_AsignarTutor_TresAñitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckb_AsignarTutor_TresAñitosActionPerformed(evt);
            }
        });
        jPanel1.add(ckb_AsignarTutor_TresAñitos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        ckb_AsignarTutor_CuatroAñitos.setText("4 Añitos");
        jPanel1.add(ckb_AsignarTutor_CuatroAñitos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        ckb_AsignarTutor_CincoAñitos.setText("5 Añitos");
        jPanel1.add(ckb_AsignarTutor_CincoAñitos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 119, 115, 280));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Primaria:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 60, -1));

        ckb_AsignarTutor_UnoPrimaria.setText("1° Prim.");
        jPanel2.add(ckb_AsignarTutor_UnoPrimaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        ckb_AsignarTutor_DosPrimaria.setText("2° Prim.");
        ckb_AsignarTutor_DosPrimaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckb_AsignarTutor_DosPrimariaActionPerformed(evt);
            }
        });
        jPanel2.add(ckb_AsignarTutor_DosPrimaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        ckb_AsignarTutor_TresPrimaria.setText("3° Prim.");
        jPanel2.add(ckb_AsignarTutor_TresPrimaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        ckb_AsignarTutor_CuatroPrimaria.setText("4° Prim.");
        jPanel2.add(ckb_AsignarTutor_CuatroPrimaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        ckb_AsignarTutor_CincoPrimaria.setText("5° Prim.");
        jPanel2.add(ckb_AsignarTutor_CincoPrimaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        ckb_AsignarTutor_SeisPrimaria.setText("6° Prim.");
        jPanel2.add(ckb_AsignarTutor_SeisPrimaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 120, 280));

        jPanel3.setBackground(new java.awt.Color(102, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Secundaria:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 70, -1));

        ckb_AsignarTutor_UnoSecundaria.setText("1° Sec.");
        jPanel3.add(ckb_AsignarTutor_UnoSecundaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        ckb_AsignarTutor_DosSecundaria.setText("2° Sec.");
        jPanel3.add(ckb_AsignarTutor_DosSecundaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        ckb_AsignarTutor_TresSecundaria.setText("3° Sec.");
        jPanel3.add(ckb_AsignarTutor_TresSecundaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        ckb_AsignarTutor_CuatroSecundaria.setText("4° Sec.");
        jPanel3.add(ckb_AsignarTutor_CuatroSecundaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        ckb_AsignarTutor_CincoSecundaria.setText("5° Sec.");
        jPanel3.add(ckb_AsignarTutor_CincoSecundaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 120, 280));

        tbl_AsignarTutor_registro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "", "", ""},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Año", "Docente", "Grados", "Código"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_AsignarTutor_registro);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 460, 390));

        jLabel1.setText("Año:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        getContentPane().add(txt_AsignarTutor_año, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, -1));

        btn_AsignarTutor_borrar.setText("Borrar");
        getContentPane().add(btn_AsignarTutor_borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 110, 30));

        cbx_AsignarTutor_Tutor1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbx_AsignarTutor_Tutor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 110, -1));

        jLabel2.setText("Tutor:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        btn_AsignarTutor_actualizar.setText("Actualizar");
        getContentPane().add(btn_AsignarTutor_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 110, 30));

        btn_AsignarTutor_crear.setText("Crear");
        getContentPane().add(btn_AsignarTutor_crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 110, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ckb_AsignarTutor_TresAñitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckb_AsignarTutor_TresAñitosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckb_AsignarTutor_TresAñitosActionPerformed

    private void ckb_AsignarTutor_DosPrimariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckb_AsignarTutor_DosPrimariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckb_AsignarTutor_DosPrimariaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AsignarTutor_actualizar;
    private javax.swing.JButton btn_AsignarTutor_borrar;
    private javax.swing.JButton btn_AsignarTutor_crear;
    private javax.swing.JComboBox<String> cbx_AsignarTutor_Tutor1;
    private javax.swing.JCheckBox ckb_AsignarTutor_CincoAñitos;
    private javax.swing.JCheckBox ckb_AsignarTutor_CincoPrimaria;
    private javax.swing.JCheckBox ckb_AsignarTutor_CincoSecundaria;
    private javax.swing.JCheckBox ckb_AsignarTutor_CuatroAñitos;
    private javax.swing.JCheckBox ckb_AsignarTutor_CuatroPrimaria;
    private javax.swing.JCheckBox ckb_AsignarTutor_CuatroSecundaria;
    private javax.swing.JCheckBox ckb_AsignarTutor_DosPrimaria;
    private javax.swing.JCheckBox ckb_AsignarTutor_DosSecundaria;
    private javax.swing.JCheckBox ckb_AsignarTutor_SeisPrimaria;
    private javax.swing.JCheckBox ckb_AsignarTutor_TresAñitos;
    private javax.swing.JCheckBox ckb_AsignarTutor_TresPrimaria;
    private javax.swing.JCheckBox ckb_AsignarTutor_TresSecundaria;
    private javax.swing.JCheckBox ckb_AsignarTutor_UnoPrimaria;
    private javax.swing.JCheckBox ckb_AsignarTutor_UnoSecundaria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_AsignarTutor_registro;
    private javax.swing.JTextField txt_AsignarTutor_año;
    // End of variables declaration//GEN-END:variables
}
