/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISTA_DIRECTIVO;

import Procesos.ExportarExcel;
import java.io.IOException;

/**
 *
 * @author SARA
 */
public class Administrar_Docente1 extends javax.swing.JFrame {

    /**
     * Creates new form frameejemplo
     */
    public Administrar_Docente1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelMaterial1 = new RSMaterialComponent.RSPanelMaterial();
        jPanel2 = new javax.swing.JPanel();
        rSLabelTextIcon2 = new RSMaterialComponent.RSLabelTextIcon();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_GD = new RSMaterialComponent.RSTableMetroCustom();
        jtxtRespuesta1 = new RSMaterialComponent.RSTextFieldTwo();
        jtxtRespuesta2 = new RSMaterialComponent.RSTextFieldTwo();
        jtxtRespuesta3 = new RSMaterialComponent.RSTextFieldTwo();
        jtxtContrass = new RSMaterialComponent.RSTextFieldTwo();
        jtxtPregunta1 = new RSMaterialComponent.RSTextFieldTwo();
        jtxtPregunta2 = new RSMaterialComponent.RSTextFieldTwo();
        jtxtPregunta3 = new RSMaterialComponent.RSTextFieldTwo();
        jtxtNDocumento = new RSMaterialComponent.RSTextFieldTwo();
        jtxtNombre = new RSMaterialComponent.RSTextFieldTwo();
        jtxtAP = new RSMaterialComponent.RSTextFieldTwo();
        jtxtAM = new RSMaterialComponent.RSTextFieldTwo();
        JbtnListarDocentes = new RSMaterialComponent.RSButtonIconShadow();
        jbtnBorrarGD = new RSMaterialComponent.RSButtonIconShadow();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jbtnEditar = new RSMaterialComponent.RSButtonIconShadow();
        jLabel14 = new javax.swing.JLabel();
        jbtnActualizarD = new RSMaterialComponent.RSButtonIconShadow();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jtxtCod = new RSMaterialComponent.RSTextFieldTwo();
        rSButtonIconShadow3 = new RSMaterialComponent.RSButtonIconShadow();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rSPanelMaterial1.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelMaterial1.setBgShade(new java.awt.Color(255, 255, 255));
        rSPanelMaterial1.setIntensity(0);
        rSPanelMaterial1.setPixels(0);
        rSPanelMaterial1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSLabelTextIcon2.setForeground(new java.awt.Color(102, 102, 255));
        rSLabelTextIcon2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSLabelTextIcon2.setText("Docente");
        rSLabelTextIcon2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ACCOUNT_BOX);
        jPanel2.add(rSLabelTextIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tbl_GD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Apellido P", " Apellido M", "Nº Documento", "Acceso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_GD.setBackgoundHead(new java.awt.Color(102, 102, 255));
        tbl_GD.setBackgoundHover(new java.awt.Color(153, 153, 255));
        tbl_GD.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tbl_GD.setFontHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tbl_GD.setFontRowHover(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tbl_GD.setFontRowSelect(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tbl_GD.setName("tbl_GD"); // NOI18N
        jScrollPane1.setViewportView(tbl_GD);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1180, 220));

        jtxtRespuesta1.setForeground(new java.awt.Color(0, 51, 102));
        jtxtRespuesta1.setBorderColor(new java.awt.Color(0, 51, 102));
        jtxtRespuesta1.setName("jtxtRespuesta1"); // NOI18N
        jtxtRespuesta1.setPhColor(new java.awt.Color(102, 102, 102));
        jtxtRespuesta1.setPlaceholder("Respuesta 1");
        jPanel2.add(jtxtRespuesta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        jtxtRespuesta2.setForeground(new java.awt.Color(0, 51, 102));
        jtxtRespuesta2.setBorderColor(new java.awt.Color(0, 51, 102));
        jtxtRespuesta2.setName("jtxtRespuesta2"); // NOI18N
        jtxtRespuesta2.setPhColor(new java.awt.Color(102, 102, 102));
        jtxtRespuesta2.setPlaceholder("Respuesta 2");
        jPanel2.add(jtxtRespuesta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, -1, -1));

        jtxtRespuesta3.setForeground(new java.awt.Color(0, 51, 102));
        jtxtRespuesta3.setBorderColor(new java.awt.Color(0, 51, 102));
        jtxtRespuesta3.setName("jtxtRespuesta3"); // NOI18N
        jtxtRespuesta3.setPhColor(new java.awt.Color(102, 102, 102));
        jtxtRespuesta3.setPlaceholder("Respuesta 3");
        jPanel2.add(jtxtRespuesta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, -1, -1));

        jtxtContrass.setForeground(new java.awt.Color(0, 51, 102));
        jtxtContrass.setBorderColor(new java.awt.Color(0, 51, 102));
        jtxtContrass.setName("jtxtContrass"); // NOI18N
        jtxtContrass.setPhColor(new java.awt.Color(102, 102, 102));
        jtxtContrass.setPlaceholder("Acceso");
        jPanel2.add(jtxtContrass, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 500, -1, -1));

        jtxtPregunta1.setForeground(new java.awt.Color(0, 51, 102));
        jtxtPregunta1.setBorderColor(new java.awt.Color(0, 51, 102));
        jtxtPregunta1.setName("jtxtPregunta1"); // NOI18N
        jtxtPregunta1.setPhColor(new java.awt.Color(102, 102, 102));
        jtxtPregunta1.setPlaceholder("Pregunta 1");
        jPanel2.add(jtxtPregunta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        jtxtPregunta2.setForeground(new java.awt.Color(0, 51, 102));
        jtxtPregunta2.setBorderColor(new java.awt.Color(0, 51, 102));
        jtxtPregunta2.setName("jtxtPregunta2"); // NOI18N
        jtxtPregunta2.setPhColor(new java.awt.Color(102, 102, 102));
        jtxtPregunta2.setPlaceholder("Pregunta 2");
        jPanel2.add(jtxtPregunta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, -1, -1));

        jtxtPregunta3.setForeground(new java.awt.Color(0, 51, 102));
        jtxtPregunta3.setBorderColor(new java.awt.Color(0, 51, 102));
        jtxtPregunta3.setName("jtxtPregunta3"); // NOI18N
        jtxtPregunta3.setPhColor(new java.awt.Color(102, 102, 102));
        jtxtPregunta3.setPlaceholder("Pregunta 3");
        jPanel2.add(jtxtPregunta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, -1, -1));

        jtxtNDocumento.setForeground(new java.awt.Color(0, 51, 102));
        jtxtNDocumento.setToolTipText("");
        jtxtNDocumento.setBorderColor(new java.awt.Color(0, 51, 102));
        jtxtNDocumento.setCaretColor(new java.awt.Color(0, 51, 102));
        jtxtNDocumento.setName("jtxtNDocumento"); // NOI18N
        jtxtNDocumento.setPhColor(new java.awt.Color(102, 102, 102));
        jtxtNDocumento.setPlaceholder("Nº de Documento");
        jtxtNDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNDocumentoActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtNDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jtxtNombre.setForeground(new java.awt.Color(0, 51, 102));
        jtxtNombre.setBorderColor(new java.awt.Color(0, 51, 102));
        jtxtNombre.setName("jtxtNombre"); // NOI18N
        jtxtNombre.setPhColor(new java.awt.Color(102, 102, 102));
        jtxtNombre.setPlaceholder("Nombre");
        jPanel2.add(jtxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, -1, -1));

        jtxtAP.setForeground(new java.awt.Color(0, 51, 102));
        jtxtAP.setBorderColor(new java.awt.Color(0, 51, 102));
        jtxtAP.setName("jtxtAP"); // NOI18N
        jtxtAP.setPhColor(new java.awt.Color(102, 102, 102));
        jtxtAP.setPlaceholder("Apellido Paterno");
        jPanel2.add(jtxtAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, -1, -1));

        jtxtAM.setForeground(new java.awt.Color(0, 51, 102));
        jtxtAM.setBorderColor(new java.awt.Color(0, 51, 102));
        jtxtAM.setName("jtxtAM"); // NOI18N
        jtxtAM.setPhColor(new java.awt.Color(102, 102, 102));
        jtxtAM.setPlaceholder("Apellido Materno");
        jPanel2.add(jtxtAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, -1, -1));

        JbtnListarDocentes.setBackground(new java.awt.Color(51, 204, 255));
        JbtnListarDocentes.setBackgroundHover(new java.awt.Color(0, 102, 153));
        JbtnListarDocentes.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.LIST);
        JbtnListarDocentes.setName("JbtnListarDocentes"); // NOI18N
        jPanel2.add(JbtnListarDocentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 350, -1, -1));

        jbtnBorrarGD.setBackground(new java.awt.Color(255, 102, 102));
        jbtnBorrarGD.setBackgroundHover(new java.awt.Color(204, 0, 0));
        jbtnBorrarGD.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE_FOREVER);
        jbtnBorrarGD.setName("jbtnBorrarGD"); // NOI18N
        jPanel2.add(jbtnBorrarGD, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 500, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Respuesta 1");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Respuesta 2");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Respuesta 3");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 480, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Acceso");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 480, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Pregunta 1");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Pregunta 2");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Pregunta 3");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Nº de Documento");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Nombre");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Apellido Paterno");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Apellido Materno");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Eliminar");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 520, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Editar");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 420, -1, -1));

        jbtnEditar.setBackground(new java.awt.Color(0, 204, 102));
        jbtnEditar.setBackgroundHover(new java.awt.Color(0, 102, 0));
        jbtnEditar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        jbtnEditar.setName("jbtnActualizarGDG"); // NOI18N
        jPanel2.add(jbtnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 400, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Actualizar");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 470, -1, -1));

        jbtnActualizarD.setBackground(new java.awt.Color(255, 204, 0));
        jbtnActualizarD.setBackgroundHover(new java.awt.Color(153, 102, 0));
        jbtnActualizarD.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);
        jbtnActualizarD.setName("jbtnActualizarGDG"); // NOI18N
        jPanel2.add(jbtnActualizarD, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 450, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Exportar PDF");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 310, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Código");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 400, -1, -1));

        jtxtCod.setEditable(false);
        jtxtCod.setForeground(new java.awt.Color(0, 51, 102));
        jtxtCod.setActionCommand("<Not Set>");
        jtxtCod.setBorderColor(new java.awt.Color(0, 51, 102));
        jtxtCod.setName("jtxtContrass"); // NOI18N
        jtxtCod.setPhColor(new java.awt.Color(102, 102, 102));
        jtxtCod.setPlaceholder("Código");
        jtxtCod.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                jtxtCodAncestorResized(evt);
            }
        });
        jPanel2.add(jtxtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 420, -1, -1));

        rSButtonIconShadow3.setBackground(new java.awt.Color(255, 102, 102));
        rSButtonIconShadow3.setBackgroundHover(new java.awt.Color(204, 0, 0));
        rSButtonIconShadow3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rSButtonIconShadow3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.RATE_REVIEW);
        rSButtonIconShadow3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconShadow3ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonIconShadow3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 300, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Listar");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 370, -1, -1));

        rSPanelMaterial1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1200, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelMaterial1, javax.swing.GroupLayout.DEFAULT_SIZE, 1226, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtNDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNDocumentoActionPerformed

    private void jtxtCodAncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jtxtCodAncestorResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCodAncestorResized
/**
     * Método que se llama cuando se hace clic en un botón (rSButtonIconShadow3).
     * Exporta los datos de un JTable (tbl_GD) a un archivo de Excel utilizando
     * la clase ExportarExcel.
     * 
     * @param evt Evento de acción que desencadena el método.
     */
    private void rSButtonIconShadow3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconShadow3ActionPerformed
             // Instancia de la clase ExportarExcel para exportar datos a Excel
        ExportarExcel obj;

        try {
            // Intenta crear una nueva instancia de ExportarExcel
            obj = new ExportarExcel();
            // Llama al método exportarExcel con el JTable tbl_GD como parámetro
            obj.exportarExcel(tbl_GD);
        } catch (IOException ex) {
            // Manejo de excepciones en caso de error durante la exportación
            System.out.println("Error: " + ex);
        }
    }//GEN-LAST:event_rSButtonIconShadow3ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public RSMaterialComponent.RSButtonIconShadow JbtnListarDocentes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public RSMaterialComponent.RSButtonIconShadow jbtnActualizarD;
    public RSMaterialComponent.RSButtonIconShadow jbtnBorrarGD;
    public RSMaterialComponent.RSButtonIconShadow jbtnEditar;
    public RSMaterialComponent.RSTextFieldTwo jtxtAM;
    public RSMaterialComponent.RSTextFieldTwo jtxtAP;
    public RSMaterialComponent.RSTextFieldTwo jtxtCod;
    public RSMaterialComponent.RSTextFieldTwo jtxtContrass;
    public RSMaterialComponent.RSTextFieldTwo jtxtNDocumento;
    public RSMaterialComponent.RSTextFieldTwo jtxtNombre;
    public RSMaterialComponent.RSTextFieldTwo jtxtPregunta1;
    public RSMaterialComponent.RSTextFieldTwo jtxtPregunta2;
    public RSMaterialComponent.RSTextFieldTwo jtxtPregunta3;
    public RSMaterialComponent.RSTextFieldTwo jtxtRespuesta1;
    public RSMaterialComponent.RSTextFieldTwo jtxtRespuesta2;
    public RSMaterialComponent.RSTextFieldTwo jtxtRespuesta3;
    public RSMaterialComponent.RSButtonIconShadow rSButtonIconShadow2;
    public RSMaterialComponent.RSButtonIconShadow rSButtonIconShadow3;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon2;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial1;
    public RSMaterialComponent.RSTableMetroCustom tbl_GD;
    // End of variables declaration//GEN-END:variables
}
