/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISTA_DIRECTIVO;

/**
 *
 * @author SARA
 */
public class Administrar_Tutor1 extends javax.swing.JFrame {

    /**
     * Creates new form frameejemplo
     */
    public Administrar_Tutor1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelMaterial1 = new RSMaterialComponent.RSPanelMaterial();
        jPanel2 = new javax.swing.JPanel();
        rSLabelTextIcon1 = new RSMaterialComponent.RSLabelTextIcon();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_AsignarTutor_registro_1 = new RSMaterialComponent.RSTableMetroCustom();
        txt_GestionarTutor_grado_1 = new RSMaterialComponent.RSTextFieldTwo();
        jLabel1 = new javax.swing.JLabel();
        btn_GestionarTutor_actualizar_1 = new RSMaterialComponent.RSButtonIconShadow();
        btn_GestionarTutor_borrar_1 = new RSMaterialComponent.RSButtonIconShadow();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rSPanelMaterial1.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelMaterial1.setAutoscrolls(true);
        rSPanelMaterial1.setBgShade(new java.awt.Color(255, 255, 255));
        rSPanelMaterial1.setPixels(0);
        rSPanelMaterial1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSLabelTextIcon1.setForeground(new java.awt.Color(102, 102, 255));
        rSLabelTextIcon1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSLabelTextIcon1.setText("Tutor");
        rSLabelTextIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FOLDER_SHARED);
        jPanel2.add(rSLabelTextIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tbl_AsignarTutor_registro_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido Paterno", "Apellido Materno", "Año", "Código", "Grado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_AsignarTutor_registro_1.setBackgoundHead(new java.awt.Color(102, 102, 255));
        tbl_AsignarTutor_registro_1.setBackgoundHover(new java.awt.Color(153, 153, 255));
        tbl_AsignarTutor_registro_1.setName("tbl_AsignarTutor_registro_1"); // NOI18N
        jScrollPane1.setViewportView(tbl_AsignarTutor_registro_1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1190, 280));

        txt_GestionarTutor_grado_1.setForeground(new java.awt.Color(0, 51, 102));
        txt_GestionarTutor_grado_1.setBorderColor(new java.awt.Color(0, 51, 102));
        txt_GestionarTutor_grado_1.setName("txt_GestionarTutor_grado_1"); // NOI18N
        txt_GestionarTutor_grado_1.setPhColor(new java.awt.Color(102, 102, 102));
        txt_GestionarTutor_grado_1.setPlaceholder("Grado");
        jPanel2.add(txt_GestionarTutor_grado_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Grado");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        btn_GestionarTutor_actualizar_1.setBackground(new java.awt.Color(255, 204, 0));
        btn_GestionarTutor_actualizar_1.setBackgroundHover(new java.awt.Color(153, 102, 0));
        btn_GestionarTutor_actualizar_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_GestionarTutor_actualizar_1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);
        btn_GestionarTutor_actualizar_1.setName("btn_GestionarTutor_actualizar_1"); // NOI18N
        jPanel2.add(btn_GestionarTutor_actualizar_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 450, -1, -1));

        btn_GestionarTutor_borrar_1.setBackground(new java.awt.Color(255, 102, 102));
        btn_GestionarTutor_borrar_1.setBackgroundHover(new java.awt.Color(204, 0, 0));
        btn_GestionarTutor_borrar_1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE_FOREVER);
        btn_GestionarTutor_borrar_1.setName("btn_GestionarTutor_borrar_1"); // NOI18N
        jPanel2.add(btn_GestionarTutor_borrar_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 500, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Actualizar");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 470, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Eliminar");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 520, -1, -1));

        rSPanelMaterial1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1200, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelMaterial1, javax.swing.GroupLayout.DEFAULT_SIZE, 1226, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public RSMaterialComponent.RSButtonIconShadow btn_GestionarTutor_actualizar_1;
    public RSMaterialComponent.RSButtonIconShadow btn_GestionarTutor_borrar_1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon1;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial1;
    public RSMaterialComponent.RSTableMetroCustom tbl_AsignarTutor_registro_1;
    public RSMaterialComponent.RSTextFieldTwo txt_GestionarTutor_grado_1;
    // End of variables declaration//GEN-END:variables
}
