/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISTA_DIRECTIVO;

/**
 *
 * @author SARA
 */
public class Asignar_Tutor extends javax.swing.JFrame {

    /**
     * Creates new form frameejemplo
     */
    public Asignar_Tutor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelMaterial1 = new RSMaterialComponent.RSPanelMaterial();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        rSLabelTextIcon1 = new RSMaterialComponent.RSLabelTextIcon();
        jLabel1 = new javax.swing.JLabel();
        txtAnio = new RSMaterialComponent.RSTextFieldTwo();
        jLabel2 = new javax.swing.JLabel();
        cbxTutor = new RSMaterialComponent.RSComboBox();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGrados = new RSMaterialComponent.RSTableMetroCustom();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProfes = new RSMaterialComponent.RSTableMetroCustom();
        btnCrear = new RSMaterialComponent.RSButtonIconShadow();
        btnActualizar = new RSMaterialComponent.RSButtonIconShadow();
        btnBorrar = new RSMaterialComponent.RSButtonIconShadow();
        btnLimpiar = new RSMaterialComponent.RSButtonIconShadow();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        panelInicial = new javax.swing.JPanel();
        Ini3 = new RSMaterialComponent.RSCheckBoxMaterial();
        Ini4 = new RSMaterialComponent.RSCheckBoxMaterial();
        Ini5 = new RSMaterialComponent.RSCheckBoxMaterial();
        panelPrimaria = new javax.swing.JPanel();
        Pri6 = new RSMaterialComponent.RSCheckBoxMaterial();
        Pri5 = new RSMaterialComponent.RSCheckBoxMaterial();
        Pri4 = new RSMaterialComponent.RSCheckBoxMaterial();
        Pri3 = new RSMaterialComponent.RSCheckBoxMaterial();
        Pri2 = new RSMaterialComponent.RSCheckBoxMaterial();
        Pri1 = new RSMaterialComponent.RSCheckBoxMaterial();
        panelSecundaria = new javax.swing.JPanel();
        Sec1 = new RSMaterialComponent.RSCheckBoxMaterial();
        Sec2 = new RSMaterialComponent.RSCheckBoxMaterial();
        Sec3 = new RSMaterialComponent.RSCheckBoxMaterial();
        Sec4 = new RSMaterialComponent.RSCheckBoxMaterial();
        Sec5 = new RSMaterialComponent.RSCheckBoxMaterial();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rSPanelMaterial1.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelMaterial1.setAutoscrolls(true);
        rSPanelMaterial1.setBgShade(new java.awt.Color(255, 255, 255));
        rSPanelMaterial1.setPixels(0);
        rSPanelMaterial1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Crear");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Eliminar");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        rSLabelTextIcon1.setForeground(new java.awt.Color(102, 102, 255));
        rSLabelTextIcon1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSLabelTextIcon1.setText("Tutor");
        rSLabelTextIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FOLDER_SHARED);
        jPanel2.add(rSLabelTextIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Año");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txtAnio.setForeground(new java.awt.Color(0, 51, 102));
        txtAnio.setBorderColor(new java.awt.Color(0, 51, 102));
        txtAnio.setName("txtAnio"); // NOI18N
        txtAnio.setPhColor(new java.awt.Color(102, 102, 102));
        txtAnio.setPlaceholder("Año");
        jPanel2.add(txtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Tutor");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        cbxTutor.setColorArrow(new java.awt.Color(153, 153, 255));
        cbxTutor.setColorBorde(new java.awt.Color(58, 66, 225));
        cbxTutor.setColorBoton(new java.awt.Color(102, 102, 255));
        cbxTutor.setColorFondo(new java.awt.Color(102, 102, 255));
        cbxTutor.setColorListaItems(new java.awt.Color(204, 204, 204));
        cbxTutor.setColorSeleccion(new java.awt.Color(102, 102, 255));
        jPanel2.add(cbxTutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Grados Asignados");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, -1));

        tblGrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Grado"
            }
        ));
        tblGrados.setBackgoundHead(new java.awt.Color(102, 102, 255));
        tblGrados.setBackgoundHover(new java.awt.Color(153, 153, 255));
        tblGrados.setName("tblGrados"); // NOI18N
        jScrollPane2.setViewportView(tblGrados);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 250, 190));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Profesores Encargados");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, -1));

        tblProfes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Año", "Código", "Nombre Docente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblProfes.setBackgoundHead(new java.awt.Color(102, 102, 255));
        tblProfes.setBackgoundHover(new java.awt.Color(153, 153, 255));
        tblProfes.setName("tblProfes"); // NOI18N
        jScrollPane1.setViewportView(tblProfes);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 720, 250));

        btnCrear.setBackground(new java.awt.Color(0, 204, 102));
        btnCrear.setBackgroundHover(new java.awt.Color(0, 102, 51));
        btnCrear.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD_CIRCLE_OUTLINE);
        btnCrear.setName("btnCrear"); // NOI18N
        jPanel2.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        btnActualizar.setBackground(new java.awt.Color(255, 204, 0));
        btnActualizar.setBackgroundHover(new java.awt.Color(153, 102, 0));
        btnActualizar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);
        btnActualizar.setName("btnActualizar"); // NOI18N
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        btnBorrar.setBackground(new java.awt.Color(255, 102, 102));
        btnBorrar.setBackgroundHover(new java.awt.Color(204, 0, 0));
        btnBorrar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE_FOREVER);
        btnBorrar.setName("btnBorrar"); // NOI18N
        jPanel2.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        btnLimpiar.setBackground(new java.awt.Color(0, 204, 255));
        btnLimpiar.setBackgroundHover(new java.awt.Color(0, 102, 153));
        btnLimpiar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE_SWEEP);
        btnLimpiar.setName("btnLimpiar"); // NOI18N
        jPanel2.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Limpiar");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Actualizar");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        panelInicial.setBackground(new java.awt.Color(249, 249, 249));
        panelInicial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

<<<<<<< HEAD
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Inicial: ");
        panelInicial.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

=======
>>>>>>> 5e918e60232b0170d66d05ce8ebeb086f0bc17db
        Ini3.setForeground(new java.awt.Color(0, 51, 102));
        Ini3.setText("3 Añitos");
        Ini3.setColorCheck(new java.awt.Color(102, 102, 255));
        Ini3.setName("Ini3"); // NOI18N
        panelInicial.add(Ini3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 110, -1));

        Ini4.setForeground(new java.awt.Color(0, 51, 102));
        Ini4.setText("4 Añitos");
        Ini4.setColorCheck(new java.awt.Color(102, 102, 255));
        Ini4.setName("Ini4"); // NOI18N
        panelInicial.add(Ini4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 110, -1));

        Ini5.setForeground(new java.awt.Color(0, 51, 102));
        Ini5.setText("5 Añitos");
        Ini5.setColorCheck(new java.awt.Color(102, 102, 255));
        Ini5.setName("Ini5"); // NOI18N
        panelInicial.add(Ini5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 110, -1));

        jPanel2.add(panelInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, 230));

        panelPrimaria.setBackground(new java.awt.Color(249, 249, 249));
        panelPrimaria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pri6.setForeground(new java.awt.Color(0, 51, 102));
        Pri6.setText("6to Grado");
        Pri6.setColorCheck(new java.awt.Color(102, 102, 255));
        Pri6.setName("Pri6"); // NOI18N
        panelPrimaria.add(Pri6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 120, -1));

        Pri5.setForeground(new java.awt.Color(0, 51, 102));
        Pri5.setText("5to Grado");
        Pri5.setColorCheck(new java.awt.Color(102, 102, 255));
        Pri5.setName("Pri5"); // NOI18N
        panelPrimaria.add(Pri5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 120, -1));

        Pri4.setForeground(new java.awt.Color(0, 51, 102));
        Pri4.setText("4to Grado");
        Pri4.setColorCheck(new java.awt.Color(102, 102, 255));
        Pri4.setName("Pri4"); // NOI18N
        panelPrimaria.add(Pri4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 120, -1));

        Pri3.setForeground(new java.awt.Color(0, 51, 102));
        Pri3.setText("3er Grado");
        Pri3.setColorCheck(new java.awt.Color(102, 102, 255));
        Pri3.setName("Pri3"); // NOI18N
        panelPrimaria.add(Pri3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 120, -1));

        Pri2.setForeground(new java.awt.Color(0, 51, 102));
        Pri2.setText("2do Grado");
        Pri2.setColorCheck(new java.awt.Color(102, 102, 255));
        Pri2.setName("Pri2"); // NOI18N
        panelPrimaria.add(Pri2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 120, -1));

        Pri1.setForeground(new java.awt.Color(0, 51, 102));
        Pri1.setText("1er Grado");
        Pri1.setColorCheck(new java.awt.Color(102, 102, 255));
        Pri1.setName("Pri1"); // NOI18N
        panelPrimaria.add(Pri1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 120, -1));

<<<<<<< HEAD
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Primaria:");
        panelPrimaria.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

=======
>>>>>>> 5e918e60232b0170d66d05ce8ebeb086f0bc17db
        jPanel2.add(panelPrimaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 120, 230));

        panelSecundaria.setBackground(new java.awt.Color(249, 249, 249));
        panelSecundaria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

<<<<<<< HEAD
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Secundaria:");
        panelSecundaria.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

=======
>>>>>>> 5e918e60232b0170d66d05ce8ebeb086f0bc17db
        Sec1.setForeground(new java.awt.Color(0, 51, 102));
        Sec1.setText("1er Año");
        Sec1.setColorCheck(new java.awt.Color(102, 102, 255));
        Sec1.setName("Sec1"); // NOI18N
        panelSecundaria.add(Sec1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 110, -1));

        Sec2.setForeground(new java.awt.Color(0, 51, 102));
        Sec2.setText("2do Año");
        Sec2.setColorCheck(new java.awt.Color(102, 102, 255));
        Sec2.setName("Sec2"); // NOI18N
        panelSecundaria.add(Sec2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 110, -1));

        Sec3.setForeground(new java.awt.Color(0, 51, 102));
        Sec3.setText("3er Año");
        Sec3.setColorCheck(new java.awt.Color(102, 102, 255));
        Sec3.setName("Sec3"); // NOI18N
        panelSecundaria.add(Sec3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 110, -1));

        Sec4.setForeground(new java.awt.Color(0, 51, 102));
        Sec4.setText("4to Año");
        Sec4.setColorCheck(new java.awt.Color(102, 102, 255));
        Sec4.setName("Sec4"); // NOI18N
        panelSecundaria.add(Sec4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 110, -1));

        Sec5.setForeground(new java.awt.Color(0, 51, 102));
        Sec5.setText("5to Año");
        Sec5.setColorCheck(new java.awt.Color(102, 102, 255));
        Sec5.setName("Sec5"); // NOI18N
        panelSecundaria.add(Sec5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 110, -1));

        jPanel2.add(panelSecundaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 110, 230));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Inicial");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Primaria");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Secundaria");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, -1));

        rSPanelMaterial1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1200, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelMaterial1, javax.swing.GroupLayout.DEFAULT_SIZE, 1226, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public RSMaterialComponent.RSCheckBoxMaterial Ini3;
    public RSMaterialComponent.RSCheckBoxMaterial Ini4;
    public RSMaterialComponent.RSCheckBoxMaterial Ini5;
    public RSMaterialComponent.RSCheckBoxMaterial Pri1;
    public RSMaterialComponent.RSCheckBoxMaterial Pri2;
    public RSMaterialComponent.RSCheckBoxMaterial Pri3;
    public RSMaterialComponent.RSCheckBoxMaterial Pri4;
    public RSMaterialComponent.RSCheckBoxMaterial Pri5;
    public RSMaterialComponent.RSCheckBoxMaterial Pri6;
    public RSMaterialComponent.RSCheckBoxMaterial Sec1;
    public RSMaterialComponent.RSCheckBoxMaterial Sec2;
    public RSMaterialComponent.RSCheckBoxMaterial Sec3;
    public RSMaterialComponent.RSCheckBoxMaterial Sec4;
    public RSMaterialComponent.RSCheckBoxMaterial Sec5;
    public RSMaterialComponent.RSButtonIconShadow btnActualizar;
    public RSMaterialComponent.RSButtonIconShadow btnBorrar;
    public RSMaterialComponent.RSButtonIconShadow btnCrear;
    public RSMaterialComponent.RSButtonIconShadow btnLimpiar;
    public RSMaterialComponent.RSComboBox cbxTutor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JPanel panelInicial;
    public javax.swing.JPanel panelPrimaria;
    public javax.swing.JPanel panelSecundaria;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon1;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial1;
    public RSMaterialComponent.RSTableMetroCustom tblGrados;
    public RSMaterialComponent.RSTableMetroCustom tblProfes;
    public RSMaterialComponent.RSTextFieldTwo txtAnio;
    // End of variables declaration//GEN-END:variables
}
