/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISTA_DIRECTIVO;

/**
 *
 * @author SARA
 */
public class Estudiante_Lista extends javax.swing.JFrame {

    /**
     * Creates new form frameejemplo
     */
    public Estudiante_Lista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelMaterial1 = new RSMaterialComponent.RSPanelMaterial();
        jPanel2 = new javax.swing.JPanel();
        rSPanelMaterial2 = new RSMaterialComponent.RSPanelMaterial();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rSLabelTextIcon1 = new RSMaterialComponent.RSLabelTextIcon();
        rSPanelMaterial3 = new RSMaterialComponent.RSPanelMaterial();
        rSPanelMaterial4 = new RSMaterialComponent.RSPanelMaterial();
        jLabel4 = new javax.swing.JLabel();
        cbxFiltrarNivel = new RSMaterialComponent.RSComboBox();
        btnFiltrar = new RSMaterialComponent.RSButtonIconShadow();
        rSButtonIconShadow2 = new RSMaterialComponent.RSButtonIconShadow();
        rSButtonIconShadow3 = new RSMaterialComponent.RSButtonIconShadow();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbxFiltrarGrado = new RSMaterialComponent.RSComboBox();
        cbxFiltrarEstadoGrado = new RSMaterialComponent.RSComboBox();
        jLabel27 = new javax.swing.JLabel();
        txtFiltrarAnio = new RSMaterialComponent.RSTextFieldTwo();
        rSPanelMaterial5 = new RSMaterialComponent.RSPanelMaterial();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaAlumnos = new RSMaterialComponent.RSTableMetroCustom();
        btnBuscar = new RSMaterialComponent.RSButtonIconShadow();
        rSPanelMaterial6 = new RSMaterialComponent.RSPanelMaterial();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtBuscar = new RSMaterialComponent.RSTextFieldTwo();
        lblNumAlumnos = new javax.swing.JLabel();
        lblNivel2 = new javax.swing.JLabel();
        rSPanelMaterial7 = new RSMaterialComponent.RSPanelMaterial();
        cbxTipoDoc = new RSMaterialComponent.RSComboBox();
        cbxGrado = new RSMaterialComponent.RSComboBox();
        txtApellidoP = new RSMaterialComponent.RSTextFieldTwo();
        txtApellidoM = new RSMaterialComponent.RSTextFieldTwo();
        cbxNivel = new RSMaterialComponent.RSComboBox();
        txtNumDoc = new RSMaterialComponent.RSTextFieldTwo();
        cbxEstadoGrado = new RSMaterialComponent.RSComboBox();
        txtAnio = new RSMaterialComponent.RSTextFieldTwo();
        btnModificarAlumno = new RSMaterialComponent.RSButtonIconShadow();
        btnCrearAlumno = new RSMaterialComponent.RSButtonIconShadow();
        btnLimpiar = new RSMaterialComponent.RSButtonIconShadow();
        lblNombres = new javax.swing.JLabel();
        lblApellidoP = new javax.swing.JLabel();
        lblApellidoM = new javax.swing.JLabel();
        lblTipoDoc = new javax.swing.JLabel();
        lblNumDoc = new javax.swing.JLabel();
        lblAnio = new javax.swing.JLabel();
        lblGradro = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtNombres = new RSMaterialComponent.RSTextFieldTwo();
        jLabel12 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        btnModificar = new RSMaterialComponent.RSButtonIconShadow();
        jLabel30 = new javax.swing.JLabel();
        btnInsertar = new RSMaterialComponent.RSButtonIconShadow();
        jLabel31 = new javax.swing.JLabel();
        btnBorrar = new RSMaterialComponent.RSButtonIconShadow();
        jLabel32 = new javax.swing.JLabel();
        lblNivel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rSPanelMaterial1.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelMaterial1.setAutoscrolls(true);
        rSPanelMaterial1.setBgShade(new java.awt.Color(255, 255, 255));
        rSPanelMaterial1.setPixels(0);
        rSPanelMaterial1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelMaterial2.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelMaterial2.setBgShade(new java.awt.Color(255, 255, 255));
        rSPanelMaterial2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Institución Educativa Privada");
        rSPanelMaterial2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 960, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MARIA REYNA DE LA PAZ");
        rSPanelMaterial2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 960, -1));

        rSLabelTextIcon1.setForeground(new java.awt.Color(102, 102, 255));
        rSLabelTextIcon1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSLabelTextIcon1.setText("Lista");
        rSLabelTextIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.LIST);
        rSLabelTextIcon1.setRequestFocusEnabled(false);
        rSPanelMaterial2.add(rSLabelTextIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel2.add(rSPanelMaterial2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 60));

        rSPanelMaterial3.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelMaterial3.setBgShade(new java.awt.Color(204, 204, 204));
        rSPanelMaterial3.setPixels(0);
        rSPanelMaterial3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelMaterial4.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelMaterial4.setBgShade(new java.awt.Color(255, 255, 255));
        rSPanelMaterial4.setPixels(0);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Nivel");

        cbxFiltrarNivel.setColorArrow(new java.awt.Color(153, 153, 255));
        cbxFiltrarNivel.setColorBorde(new java.awt.Color(58, 66, 225));
        cbxFiltrarNivel.setColorBoton(new java.awt.Color(102, 102, 255));
        cbxFiltrarNivel.setColorFondo(new java.awt.Color(102, 102, 255));
        cbxFiltrarNivel.setColorListaItems(new java.awt.Color(204, 204, 204));
        cbxFiltrarNivel.setColorSeleccion(new java.awt.Color(102, 102, 255));
        cbxFiltrarNivel.setName("cbxFiltrarNivel"); // NOI18N

        btnFiltrar.setBackground(new java.awt.Color(0, 102, 204));
        btnFiltrar.setBackgroundHover(new java.awt.Color(0, 51, 102));
        btnFiltrar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILTER_LIST);
        btnFiltrar.setName("btnFiltrar"); // NOI18N

        rSButtonIconShadow2.setBackground(new java.awt.Color(255, 102, 102));
        rSButtonIconShadow2.setBackgroundHover(new java.awt.Color(204, 0, 0));
        rSButtonIconShadow2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rSButtonIconShadow2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.RATE_REVIEW);

        rSButtonIconShadow3.setBackground(new java.awt.Color(255, 153, 51));
        rSButtonIconShadow3.setBackgroundHover(new java.awt.Color(145, 72, 0));
        rSButtonIconShadow3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.COMMENT);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Grado");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Estado");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Exportar a PDF");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Resumen del Bimestre");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Filtro");

        cbxFiltrarGrado.setColorArrow(new java.awt.Color(153, 153, 255));
        cbxFiltrarGrado.setColorBorde(new java.awt.Color(58, 66, 225));
        cbxFiltrarGrado.setColorBoton(new java.awt.Color(102, 102, 255));
        cbxFiltrarGrado.setColorFondo(new java.awt.Color(102, 102, 255));
        cbxFiltrarGrado.setColorListaItems(new java.awt.Color(204, 204, 204));
        cbxFiltrarGrado.setColorSeleccion(new java.awt.Color(102, 102, 255));
        cbxFiltrarGrado.setName("cbxFiltrarGrado"); // NOI18N

        cbxFiltrarEstadoGrado.setColorArrow(new java.awt.Color(153, 153, 255));
        cbxFiltrarEstadoGrado.setColorBorde(new java.awt.Color(58, 66, 225));
        cbxFiltrarEstadoGrado.setColorBoton(new java.awt.Color(102, 102, 255));
        cbxFiltrarEstadoGrado.setColorFondo(new java.awt.Color(102, 102, 255));
        cbxFiltrarEstadoGrado.setColorListaItems(new java.awt.Color(204, 204, 204));
        cbxFiltrarEstadoGrado.setColorSeleccion(new java.awt.Color(102, 102, 255));
        cbxFiltrarEstadoGrado.setName("cbxFiltrarEstadoGrado"); // NOI18N

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("Año");

        txtFiltrarAnio.setForeground(new java.awt.Color(0, 51, 102));
        txtFiltrarAnio.setBorderColor(new java.awt.Color(0, 51, 102));
        txtFiltrarAnio.setCaretColor(new java.awt.Color(0, 51, 102));
        txtFiltrarAnio.setName("txtFiltrarAnio"); // NOI18N
        txtFiltrarAnio.setPhColor(new java.awt.Color(102, 102, 102));
        txtFiltrarAnio.setPlaceholder("Año");
        txtFiltrarAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiltrarAnioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rSPanelMaterial4Layout = new javax.swing.GroupLayout(rSPanelMaterial4);
        rSPanelMaterial4.setLayout(rSPanelMaterial4Layout);
        rSPanelMaterial4Layout.setHorizontalGroup(
            rSPanelMaterial4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelMaterial4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelMaterial4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxFiltrarNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(cbxFiltrarGrado, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cbxFiltrarEstadoGrado, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(txtFiltrarAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(rSPanelMaterial4Layout.createSequentialGroup()
                .addGroup(rSPanelMaterial4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelMaterial4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rSButtonIconShadow2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelMaterial4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rSButtonIconShadow3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelMaterial4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        rSPanelMaterial4Layout.setVerticalGroup(
            rSPanelMaterial4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelMaterial4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxFiltrarNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxFiltrarGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxFiltrarEstadoGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFiltrarAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(rSPanelMaterial4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rSPanelMaterial4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel9)))
                .addGroup(rSPanelMaterial4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelMaterial4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rSButtonIconShadow2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rSPanelMaterial4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)))
                .addGroup(rSPanelMaterial4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelMaterial4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rSButtonIconShadow3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rSPanelMaterial4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel8))))
        );

        rSPanelMaterial3.add(rSPanelMaterial4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 420));

        rSPanelMaterial5.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelMaterial5.setBgShade(new java.awt.Color(215, 215, 215));
        rSPanelMaterial5.setPixels(0);
        rSPanelMaterial5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblListaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "aNDRADEHIDALGO SARA AMALIA DE LOS ANGELES", "ENERO"},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nº", "Apellidos y Nombres", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblListaAlumnos.setBackgoundHead(new java.awt.Color(102, 102, 255));
        tblListaAlumnos.setBackgoundHover(new java.awt.Color(153, 153, 255));
        tblListaAlumnos.setName("tblListaAlumnos"); // NOI18N
        jScrollPane1.setViewportView(tblListaAlumnos);

        rSPanelMaterial5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 81, 362, 222));

        btnBuscar.setBackground(new java.awt.Color(102, 102, 102));
        btnBuscar.setBackgroundHover(new java.awt.Color(204, 204, 204));
        btnBuscar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        btnBuscar.setName("btnBuscar"); // NOI18N
        rSPanelMaterial5.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));

        rSPanelMaterial6.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelMaterial6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Leyenda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        rSPanelMaterial6.setForeground(new java.awt.Color(255, 255, 255));
        rSPanelMaterial6.setBgShade(new java.awt.Color(255, 255, 255));
        rSPanelMaterial6.setPixels(0);
        rSPanelMaterial6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Aprobado");
        rSPanelMaterial6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("En Curso");
        rSPanelMaterial6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Retirado");
        rSPanelMaterial6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 0));
        jLabel14.setText("0");
        rSPanelMaterial6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("0");
        rSPanelMaterial6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 204, 255));
        jLabel16.setText("0");
        rSPanelMaterial6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 51, 51));
        jLabel33.setText("Pendiente");
        rSPanelMaterial6.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 51, 51));
        jLabel34.setText("0");
        rSPanelMaterial6.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        rSPanelMaterial5.add(rSPanelMaterial6, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 320, 120, 150));

        txtBuscar.setForeground(new java.awt.Color(0, 51, 102));
        txtBuscar.setBorderColor(new java.awt.Color(0, 51, 102));
        txtBuscar.setCaretColor(new java.awt.Color(0, 51, 102));
        txtBuscar.setName("txtBuscar"); // NOI18N
        txtBuscar.setPhColor(new java.awt.Color(102, 102, 102));
        txtBuscar.setPlaceholder("Buscar Estudiante");
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        rSPanelMaterial5.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 320, -1));

        lblNumAlumnos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNumAlumnos.setForeground(new java.awt.Color(102, 102, 102));
        lblNumAlumnos.setText("NumAlumnos");
        rSPanelMaterial5.add(lblNumAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        lblNivel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNivel2.setForeground(new java.awt.Color(102, 102, 102));
        lblNivel2.setText("Listado de estudiantes: ");
        rSPanelMaterial5.add(lblNivel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        rSPanelMaterial3.add(rSPanelMaterial5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 450, 470));

        rSPanelMaterial7.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelMaterial7.setBgShade(new java.awt.Color(255, 255, 255));
        rSPanelMaterial7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxTipoDoc.setColorArrow(new java.awt.Color(153, 153, 255));
        cbxTipoDoc.setColorBorde(new java.awt.Color(58, 66, 225));
        cbxTipoDoc.setColorBoton(new java.awt.Color(102, 102, 255));
        cbxTipoDoc.setColorFondo(new java.awt.Color(102, 102, 255));
        cbxTipoDoc.setColorListaItems(new java.awt.Color(204, 204, 204));
        cbxTipoDoc.setColorSeleccion(new java.awt.Color(102, 102, 255));
        cbxTipoDoc.setName("cbxTipoDoc"); // NOI18N
        rSPanelMaterial7.add(cbxTipoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 139, -1));

        cbxGrado.setColorArrow(new java.awt.Color(153, 153, 255));
        cbxGrado.setColorBorde(new java.awt.Color(58, 66, 225));
        cbxGrado.setColorBoton(new java.awt.Color(102, 102, 255));
        cbxGrado.setColorFondo(new java.awt.Color(102, 102, 255));
        cbxGrado.setColorListaItems(new java.awt.Color(204, 204, 204));
        cbxGrado.setColorSeleccion(new java.awt.Color(102, 102, 255));
        cbxGrado.setName("cbxGrado"); // NOI18N
        rSPanelMaterial7.add(cbxGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 110, -1));

        txtApellidoP.setForeground(new java.awt.Color(0, 51, 102));
        txtApellidoP.setBorderColor(new java.awt.Color(0, 51, 102));
        txtApellidoP.setCaretColor(new java.awt.Color(0, 51, 102));
        txtApellidoP.setName("txtApellidoP"); // NOI18N
        txtApellidoP.setPhColor(new java.awt.Color(102, 102, 102));
        txtApellidoP.setPlaceholder("Apellido Paterno");
        rSPanelMaterial7.add(txtApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 134, 30));

        txtApellidoM.setForeground(new java.awt.Color(0, 51, 102));
        txtApellidoM.setBorderColor(new java.awt.Color(0, 51, 102));
        txtApellidoM.setCaretColor(new java.awt.Color(0, 51, 102));
        txtApellidoM.setName("txtApellidoM"); // NOI18N
        txtApellidoM.setPhColor(new java.awt.Color(102, 102, 102));
        txtApellidoM.setPlaceholder("Apellido Materno");
        rSPanelMaterial7.add(txtApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 141, 30));

        cbxNivel.setColorArrow(new java.awt.Color(153, 153, 255));
        cbxNivel.setColorBorde(new java.awt.Color(58, 66, 225));
        cbxNivel.setColorBoton(new java.awt.Color(102, 102, 255));
        cbxNivel.setColorFondo(new java.awt.Color(102, 102, 255));
        cbxNivel.setColorListaItems(new java.awt.Color(204, 204, 204));
        cbxNivel.setColorSeleccion(new java.awt.Color(102, 102, 255));
        cbxNivel.setName("cbxNivel"); // NOI18N
        rSPanelMaterial7.add(cbxNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 110, -1));

        txtNumDoc.setForeground(new java.awt.Color(0, 51, 102));
        txtNumDoc.setBorderColor(new java.awt.Color(0, 51, 102));
        txtNumDoc.setCaretColor(new java.awt.Color(0, 51, 102));
        txtNumDoc.setName("txtNumDoc"); // NOI18N
        txtNumDoc.setPhColor(new java.awt.Color(102, 102, 102));
        txtNumDoc.setPlaceholder("Número de Documento");
        rSPanelMaterial7.add(txtNumDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 180, 30));

        cbxEstadoGrado.setColorArrow(new java.awt.Color(153, 153, 255));
        cbxEstadoGrado.setColorBorde(new java.awt.Color(58, 66, 225));
        cbxEstadoGrado.setColorBoton(new java.awt.Color(102, 102, 255));
        cbxEstadoGrado.setColorFondo(new java.awt.Color(102, 102, 255));
        cbxEstadoGrado.setColorListaItems(new java.awt.Color(204, 204, 204));
        cbxEstadoGrado.setColorSeleccion(new java.awt.Color(102, 102, 255));
        cbxEstadoGrado.setName("cbxEstadoGrado"); // NOI18N
        rSPanelMaterial7.add(cbxEstadoGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 110, -1));

        txtAnio.setForeground(new java.awt.Color(0, 51, 102));
        txtAnio.setBorderColor(new java.awt.Color(0, 51, 102));
        txtAnio.setCaretColor(new java.awt.Color(0, 51, 102));
        txtAnio.setName("txtAnio"); // NOI18N
        txtAnio.setPhColor(new java.awt.Color(102, 102, 102));
        txtAnio.setPlaceholder("Año");
        rSPanelMaterial7.add(txtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 322, 70, 30));

        btnModificarAlumno.setBackground(new java.awt.Color(255, 153, 51));
        btnModificarAlumno.setBackgroundHover(new java.awt.Color(145, 72, 0));
        btnModificarAlumno.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CREATE);
        btnModificarAlumno.setName("btnModificarAlumno"); // NOI18N
        rSPanelMaterial7.add(btnModificarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        btnCrearAlumno.setBackground(new java.awt.Color(0, 204, 102));
        btnCrearAlumno.setBackgroundHover(new java.awt.Color(0, 102, 51));
        btnCrearAlumno.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD_CIRCLE_OUTLINE);
        btnCrearAlumno.setName("btnCrearAlumno"); // NOI18N
        rSPanelMaterial7.add(btnCrearAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        btnLimpiar.setBackground(new java.awt.Color(0, 204, 255));
        btnLimpiar.setBackgroundHover(new java.awt.Color(0, 102, 153));
        btnLimpiar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE_SWEEP);
        btnLimpiar.setName("btnLimpiar"); // NOI18N
        rSPanelMaterial7.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, -1, -1));

        lblNombres.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNombres.setForeground(new java.awt.Color(102, 102, 102));
        lblNombres.setText("Nombres");
        rSPanelMaterial7.add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        lblApellidoP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblApellidoP.setForeground(new java.awt.Color(102, 102, 102));
        lblApellidoP.setText("Apellido Paterno");
        rSPanelMaterial7.add(lblApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        lblApellidoM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblApellidoM.setForeground(new java.awt.Color(102, 102, 102));
        lblApellidoM.setText("Apellido Materno");
        rSPanelMaterial7.add(lblApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        lblTipoDoc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTipoDoc.setForeground(new java.awt.Color(102, 102, 102));
        lblTipoDoc.setText("Tipo de Documento");
        rSPanelMaterial7.add(lblTipoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        lblNumDoc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNumDoc.setForeground(new java.awt.Color(102, 102, 102));
        lblNumDoc.setText("Número de Documento");
        rSPanelMaterial7.add(lblNumDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        lblAnio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAnio.setForeground(new java.awt.Color(102, 102, 102));
        lblAnio.setText("Año");
        rSPanelMaterial7.add(lblAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, -1, 10));

        lblGradro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGradro.setForeground(new java.awt.Color(102, 102, 102));
        lblGradro.setText("Grado");
        rSPanelMaterial7.add(lblGradro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        lblEstado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(102, 102, 102));
        lblEstado.setText("Estado");
        rSPanelMaterial7.add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("Modificar");
        rSPanelMaterial7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("Agregar");
        rSPanelMaterial7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("Limpiar");
        rSPanelMaterial7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));

        txtNombres.setForeground(new java.awt.Color(0, 51, 102));
        txtNombres.setBorderColor(new java.awt.Color(0, 51, 102));
        txtNombres.setCaretColor(new java.awt.Color(0, 51, 102));
        txtNombres.setName("txtNombres"); // NOI18N
        txtNombres.setPhColor(new java.awt.Color(102, 102, 102));
        txtNombres.setPlaceholder("Nombres");
        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        rSPanelMaterial7.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 139, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Información del Grado");
        rSPanelMaterial7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 410, -1));

        titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(102, 102, 102));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titulo.setText("Información del alumno");
        rSPanelMaterial7.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, -1));

        btnModificar.setBackground(new java.awt.Color(255, 153, 51));
        btnModificar.setBackgroundHover(new java.awt.Color(145, 72, 0));
        btnModificar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CREATE);
        btnModificar.setName("btnModificar"); // NOI18N
        rSPanelMaterial7.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(102, 102, 102));
        jLabel30.setText("Modificar");
        rSPanelMaterial7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        btnInsertar.setBackground(new java.awt.Color(0, 204, 102));
        btnInsertar.setBackgroundHover(new java.awt.Color(0, 102, 51));
        btnInsertar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD_CIRCLE_OUTLINE);
        btnInsertar.setName("btnInsertar"); // NOI18N
        rSPanelMaterial7.add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setText("Agregar");
        rSPanelMaterial7.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, -1, -1));

        btnBorrar.setBackground(new java.awt.Color(255, 102, 102));
        btnBorrar.setBackgroundHover(new java.awt.Color(204, 0, 0));
        btnBorrar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE_FOREVER);
        btnBorrar.setName("btnBorrar"); // NOI18N
        rSPanelMaterial7.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(102, 102, 102));
        jLabel32.setText("Eliminar");
        rSPanelMaterial7.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, -1, -1));

        lblNivel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNivel1.setForeground(new java.awt.Color(102, 102, 102));
        lblNivel1.setText("Nivel");
        rSPanelMaterial7.add(lblNivel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        rSPanelMaterial3.add(rSPanelMaterial7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 470, 460));

        jPanel2.add(rSPanelMaterial3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1190, 490));

        rSPanelMaterial1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1200, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelMaterial1, javax.swing.GroupLayout.DEFAULT_SIZE, 1226, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFiltrarAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiltrarAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiltrarAnioActionPerformed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public RSMaterialComponent.RSButtonIconShadow btnBorrar;
    public RSMaterialComponent.RSButtonIconShadow btnBuscar;
    public RSMaterialComponent.RSButtonIconShadow btnCrearAlumno;
    public RSMaterialComponent.RSButtonIconShadow btnFiltrar;
    public RSMaterialComponent.RSButtonIconShadow btnInsertar;
    public RSMaterialComponent.RSButtonIconShadow btnLimpiar;
    public RSMaterialComponent.RSButtonIconShadow btnModificar;
    public RSMaterialComponent.RSButtonIconShadow btnModificarAlumno;
    public RSMaterialComponent.RSComboBox cbxEstadoGrado;
    public RSMaterialComponent.RSComboBox cbxFiltrarEstadoGrado;
    public RSMaterialComponent.RSComboBox cbxFiltrarGrado;
    public RSMaterialComponent.RSComboBox cbxFiltrarNivel;
    public RSMaterialComponent.RSComboBox cbxGrado;
    public RSMaterialComponent.RSComboBox cbxNivel;
    public RSMaterialComponent.RSComboBox cbxTipoDoc;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    public javax.swing.JLabel jLabel33;
    public javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblApellidoM;
    private javax.swing.JLabel lblApellidoP;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblGradro;
    private javax.swing.JLabel lblNivel1;
    private javax.swing.JLabel lblNivel2;
    private javax.swing.JLabel lblNombres;
    public javax.swing.JLabel lblNumAlumnos;
    private javax.swing.JLabel lblNumDoc;
    private javax.swing.JLabel lblTipoDoc;
    public RSMaterialComponent.RSButtonIconShadow rSButtonIconShadow2;
    public RSMaterialComponent.RSButtonIconShadow rSButtonIconShadow3;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon1;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial1;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial2;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial3;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial4;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial5;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial6;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial7;
    public RSMaterialComponent.RSTableMetroCustom tblListaAlumnos;
    private javax.swing.JLabel titulo;
    public RSMaterialComponent.RSTextFieldTwo txtAnio;
    public RSMaterialComponent.RSTextFieldTwo txtApellidoM;
    public RSMaterialComponent.RSTextFieldTwo txtApellidoP;
    public RSMaterialComponent.RSTextFieldTwo txtBuscar;
    public RSMaterialComponent.RSTextFieldTwo txtFiltrarAnio;
    public RSMaterialComponent.RSTextFieldTwo txtNombres;
    public RSMaterialComponent.RSTextFieldTwo txtNumDoc;
    // End of variables declaration//GEN-END:variables
}
