/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.AdministrarCuenta;

/**
 *
 * @author SARA
 */
public class tabContent2 extends javax.swing.JPanel {

    /**
     * Creates new form tabContent2
     */
    public tabContent2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSLabelTextIcon1 = new RSMaterialComponent.RSLabelTextIcon();
        jtxtBuscar = new RSMaterialComponent.RSTextFieldMaterialIcon();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_AsignarTutor_registro_1 = new RSMaterialComponent.RSTableMetroCustom();
        txt_GestionarTutor_grado_1 = new RSMaterialComponent.RSTextFieldTwo();
        btn_GestionarTutor_borrar_1 = new RSMaterialComponent.RSButtonIconShadow();
        jLabel1 = new javax.swing.JLabel();
        btn_GestionarTutor_actualizar_1 = new RSMaterialComponent.RSButtonIconShadow();

        setBackground(new java.awt.Color(255, 255, 255));

        rSLabelTextIcon1.setForeground(new java.awt.Color(102, 102, 255));
        rSLabelTextIcon1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSLabelTextIcon1.setText("Tutor");
        rSLabelTextIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FOLDER_SHARED);

        jtxtBuscar.setForeground(new java.awt.Color(153, 153, 153));
        jtxtBuscar.setColorIcon(new java.awt.Color(51, 51, 51));
        jtxtBuscar.setColorMaterial(new java.awt.Color(153, 153, 153));
        jtxtBuscar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        jtxtBuscar.setName("jtxtBuscar"); // NOI18N
        jtxtBuscar.setPlaceholder("Buscar");

        tbl_AsignarTutor_registro_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido Paterno", "Apellido Materno", "Año", "Código", "Grado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_AsignarTutor_registro_1.setBackgoundHead(new java.awt.Color(102, 102, 255));
        tbl_AsignarTutor_registro_1.setBackgoundHover(new java.awt.Color(153, 153, 255));
        tbl_AsignarTutor_registro_1.setName("tbl_AsignarTutor_registro_1"); // NOI18N
        jScrollPane1.setViewportView(tbl_AsignarTutor_registro_1);

        txt_GestionarTutor_grado_1.setForeground(new java.awt.Color(0, 51, 102));
        txt_GestionarTutor_grado_1.setBorderColor(new java.awt.Color(0, 51, 102));
        txt_GestionarTutor_grado_1.setName("txt_GestionarTutor_grado_1"); // NOI18N
        txt_GestionarTutor_grado_1.setPhColor(new java.awt.Color(102, 102, 102));
        txt_GestionarTutor_grado_1.setPlaceholder("Grado");

        btn_GestionarTutor_borrar_1.setBackground(new java.awt.Color(255, 102, 102));
        btn_GestionarTutor_borrar_1.setBackgroundHover(new java.awt.Color(204, 0, 0));
        btn_GestionarTutor_borrar_1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE_FOREVER);
        btn_GestionarTutor_borrar_1.setName("btn_GestionarTutor_borrar_1"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Grado");

        btn_GestionarTutor_actualizar_1.setBackground(new java.awt.Color(255, 204, 0));
        btn_GestionarTutor_actualizar_1.setBackgroundHover(new java.awt.Color(153, 102, 0));
        btn_GestionarTutor_actualizar_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_GestionarTutor_actualizar_1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);
        btn_GestionarTutor_actualizar_1.setName("btn_GestionarTutor_actualizar_1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_GestionarTutor_grado_1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_GestionarTutor_actualizar_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_GestionarTutor_borrar_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_GestionarTutor_actualizar_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_GestionarTutor_grado_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_GestionarTutor_borrar_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public RSMaterialComponent.RSButtonIconShadow btn_GestionarTutor_actualizar_1;
    public RSMaterialComponent.RSButtonIconShadow btn_GestionarTutor_borrar_1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public RSMaterialComponent.RSTextFieldMaterialIcon jtxtBuscar;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon1;
    public RSMaterialComponent.RSTableMetroCustom tbl_AsignarTutor_registro_1;
    public RSMaterialComponent.RSTextFieldTwo txt_GestionarTutor_grado_1;
    // End of variables declaration//GEN-END:variables
}
