/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import java.awt.Dimension;

public class crear_cuenta_docentes_directivo_1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form crear_cuenta_docentes_directivo_1
     */
    public crear_cuenta_docentes_directivo_1() {
        initComponents();
        this.setSize(new Dimension(575, 832));//TAMANO DEL FORMULARIO SUS DIMENSIONES
        this.setTitle("Crear cuanta doceentes");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Jtxtnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNumDocumento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldApellidoP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldApellidoM = new javax.swing.JTextField();
        jbtnRegistrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldPregunta1 = new javax.swing.JTextField();
        jTextFieldRespuesta1 = new javax.swing.JTextField();
        jTextFieldPregunta2 = new javax.swing.JTextField();
        jTextFieldRespuesta2 = new javax.swing.JTextField();
        jTextFieldRespuesta3 = new javax.swing.JTextField();
        jTextFieldPregunta3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        textFieldClave2 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldClave = new javax.swing.JPasswordField();

        setMaximizable(true);
        setAutoscrolls(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Datos Personales del docente:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 20));

        jLabel2.setText("Ingrese su nombre completo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));
        getContentPane().add(Jtxtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 160, 30));

        jLabel3.setText("Ingrese su apellido paterno:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));
        getContentPane().add(jTextFieldNumDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 160, 30));

        jLabel4.setText("Ingrese su apellido materno:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        getContentPane().add(jTextFieldApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 160, 30));

        jLabel5.setText("Ingrese su DNI:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));
        getContentPane().add(jTextFieldApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 160, 30));

        jbtnRegistrar.setText("REGISTRAR");
        jbtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 120, 80));

        jLabel6.setText("Ingrese los cursos en los que se encuentra calificado:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jCheckBox1.setText("Ciencia y tecnologia");
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, -1, -1));

        jCheckBox2.setText("Matematicas");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jCheckBox3.setText("Personal Social");
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jCheckBox4.setText("Arte y cultura");
        getContentPane().add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        jCheckBox5.setText("Comunicación");
        getContentPane().add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, -1));

        jCheckBox6.setText("Ciencias Sociales");
        getContentPane().add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        jCheckBox7.setText("Educa.Fisica");
        getContentPane().add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, -1));

        jCheckBox8.setText("Ingles");
        getContentPane().add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));

        jCheckBox9.setText("Religion");
        getContentPane().add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, -1));

        jCheckBox10.setText("Computación");
        getContentPane().add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, -1, -1));

        jCheckBox11.setText("Desarrollo personal ciudadanía y cívica");
        getContentPane().add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, -1, -1));

        jCheckBox12.setText("Educación para el trabajo");
        getContentPane().add(jCheckBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, -1, -1));

        jLabel7.setText("Ingrese 5 preguntas para la recuperación de su contraseña en caso de un olvido");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        jTextFieldPregunta1.setText("Pregunta 1");
        jTextFieldPregunta1.setToolTipText("");
        getContentPane().add(jTextFieldPregunta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 250, 30));

        jTextFieldRespuesta1.setText("Respuesta 1");
        getContentPane().add(jTextFieldRespuesta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 250, 30));

        jTextFieldPregunta2.setText("Pregunta 2");
        getContentPane().add(jTextFieldPregunta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 250, 30));

        jTextFieldRespuesta2.setText("Respuesta 2");
        getContentPane().add(jTextFieldRespuesta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 250, 30));

        jTextFieldRespuesta3.setText("Pregunta 3");
        getContentPane().add(jTextFieldRespuesta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, 250, 30));

        jTextFieldPregunta3.setText("Respuesta 3");
        getContentPane().add(jTextFieldPregunta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 250, 30));

        jLabel11.setText("Crease una contraseña:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, -1, -1));
        getContentPane().add(textFieldClave2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 760, 170, 30));

        jLabel9.setText("La contraseña debe de contener mayusculas, minusculas, números y signos especiales");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 680, -1, -1));

        jLabel10.setText("verifique su contraseña:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 740, -1, -1));
        getContentPane().add(jTextFieldClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 700, 170, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jbtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Jtxtnombre;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField jTextFieldApellidoM;
    public javax.swing.JTextField jTextFieldApellidoP;
    public javax.swing.JPasswordField jTextFieldClave;
    public javax.swing.JTextField jTextFieldNumDocumento;
    public javax.swing.JTextField jTextFieldPregunta1;
    public javax.swing.JTextField jTextFieldPregunta2;
    public javax.swing.JTextField jTextFieldPregunta3;
    public javax.swing.JTextField jTextFieldRespuesta1;
    public javax.swing.JTextField jTextFieldRespuesta2;
    public javax.swing.JTextField jTextFieldRespuesta3;
    public javax.swing.JButton jbtnRegistrar;
    public javax.swing.JPasswordField textFieldClave2;
    // End of variables declaration//GEN-END:variables
}
