/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import java.awt.Dimension;

public class crear_cuenta_docentes_directivo_1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form crear_cuenta_docentes_directivo_1
     */
    public crear_cuenta_docentes_directivo_1() {
        initComponents();
        this.setSize(new Dimension(575, 832));//TAMANO DEL FORMULARIO SUS DIMENSIONES
        this.setTitle("Crear cuanta doceentes");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Jtxtnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNumDocumento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldApellidoP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldApellidoM = new javax.swing.JTextField();
        jbtnRegistrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cb_CienciaTecnologia = new javax.swing.JCheckBox();
        cb_matematica = new javax.swing.JCheckBox();
        cb_PersonalSocial = new javax.swing.JCheckBox();
        cb_ArteCultura = new javax.swing.JCheckBox();
        cb_comunicacion = new javax.swing.JCheckBox();
        cb_CienciasSociales = new javax.swing.JCheckBox();
        cb_EduFisica = new javax.swing.JCheckBox();
        cb_ingles = new javax.swing.JCheckBox();
        cb_psicomotriz = new javax.swing.JCheckBox();
        cb_computacion = new javax.swing.JCheckBox();
        cb_CiudadaniaCivica = new javax.swing.JCheckBox();
        cb_EduTrabajo = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldRespuesta1 = new javax.swing.JTextField();
        jTextFieldRespuesta2 = new javax.swing.JTextField();
        jTextFieldRespuesta3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        textFieldClave2 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldClave = new javax.swing.JPasswordField();
        jTextFieldPregunta1 = new javax.swing.JComboBox<>();
        jTextFieldPregunta2 = new javax.swing.JComboBox<>();
        jTextFieldPregunta3 = new javax.swing.JComboBox<>();
        cb_religion1 = new javax.swing.JCheckBox();

        setMaximizable(true);
        setAutoscrolls(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Datos Personales del docente:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 20));

        jLabel2.setText("Ingrese su nombre completo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));
        getContentPane().add(Jtxtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 160, 30));

        jLabel3.setText("Ingrese su apellido paterno:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, 20));
        getContentPane().add(jTextFieldNumDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 160, 30));

        jLabel4.setText("Ingrese su apellido materno:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        getContentPane().add(jTextFieldApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 160, 30));

        jLabel5.setText("Ingrese su DNI:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));
        getContentPane().add(jTextFieldApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 160, 30));

        jbtnRegistrar.setText("REGISTRAR");
        jbtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 120, 40));

        jLabel6.setText("Ingrese los cursos en los que se encuentra calificado:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        cb_CienciaTecnologia.setText("Ciencia y tecnologia");
        getContentPane().add(cb_CienciaTecnologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        cb_matematica.setText("Matematicas");
        cb_matematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_matematicaActionPerformed(evt);
            }
        });
        getContentPane().add(cb_matematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        cb_PersonalSocial.setText("Personal Social");
        getContentPane().add(cb_PersonalSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        cb_ArteCultura.setText("Arte y cultura");
        getContentPane().add(cb_ArteCultura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        cb_comunicacion.setText("Comunicación");
        getContentPane().add(cb_comunicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        cb_CienciasSociales.setText("Ciencias Sociales");
        getContentPane().add(cb_CienciasSociales, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        cb_EduFisica.setText("Educa.Fisica");
        getContentPane().add(cb_EduFisica, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        cb_ingles.setText("Ingles");
        getContentPane().add(cb_ingles, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        cb_psicomotriz.setText("Psicomotriz");
        getContentPane().add(cb_psicomotriz, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, -1));

        cb_computacion.setText("Computación");
        getContentPane().add(cb_computacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        cb_CiudadaniaCivica.setText("Desarrollo personal ciudadanía y cívica");
        getContentPane().add(cb_CiudadaniaCivica, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        cb_EduTrabajo.setText("Educación para el trabajo");
        getContentPane().add(cb_EduTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        jLabel7.setText("Ingrese 5 preguntas para la recuperación de su contraseña en caso de un olvido");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));
        getContentPane().add(jTextFieldRespuesta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 250, 30));
        getContentPane().add(jTextFieldRespuesta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 250, 30));

        jTextFieldRespuesta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRespuesta3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldRespuesta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 250, 30));

        jLabel11.setText("Crease una contraseña:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));
        getContentPane().add(textFieldClave2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 170, 30));

        jLabel9.setText("La contraseña debe de contener mayusculas, minusculas, números y signos especiales");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        jLabel10.setText("verifique su contraseña:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, -1, -1));
        getContentPane().add(jTextFieldClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 170, 30));

        jTextFieldPregunta1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "¿Dónde realizaste tus prácticas docentes?", "¿En qué año comenzaste a trabajar como docente en la institución actual?", "¿En qué institución educativa diste tu primera clase como docente?", "¿Cuál es el nombre de tu profesor/a favorito/a durante tus estudios?", "¿Qué asignatura o materia enseñabas en tu primer año como docente" }));
        getContentPane().add(jTextFieldPregunta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 280, 30));

        jTextFieldPregunta2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "¿Dónde realizaste tus prácticas docentes?", "¿En qué año comenzaste a trabajar como docente en la institución actual?", "¿En qué institución educativa diste tu primera clase como docente?", "¿Cuál es el nombre de tu profesor/a favorito/a durante tus estudios?", "¿Qué asignatura o materia enseñabas en tu primer año como docente" }));
        getContentPane().add(jTextFieldPregunta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 280, 30));

        jTextFieldPregunta3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "¿Dónde realizaste tus prácticas docentes?", "¿En qué año comenzaste a trabajar como docente en la institución actual?", "¿En qué institución educativa diste tu primera clase como docente?", "¿Cuál es el nombre de tu profesor/a favorito/a durante tus estudios?", "¿Qué asignatura o materia enseñabas en tu primer año como docente" }));
        getContentPane().add(jTextFieldPregunta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 280, 30));

        cb_religion1.setText("Religion");
        getContentPane().add(cb_religion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnRegistrarActionPerformed

    private void cb_matematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_matematicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_matematicaActionPerformed

    private void jTextFieldRespuesta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRespuesta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRespuesta3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Jtxtnombre;
    public javax.swing.JCheckBox cb_ArteCultura;
    public javax.swing.JCheckBox cb_CienciaTecnologia;
    public javax.swing.JCheckBox cb_CienciasSociales;
    public javax.swing.JCheckBox cb_CiudadaniaCivica;
    public javax.swing.JCheckBox cb_EduFisica;
    public javax.swing.JCheckBox cb_EduTrabajo;
    public javax.swing.JCheckBox cb_PersonalSocial;
    public javax.swing.JCheckBox cb_computacion;
    public javax.swing.JCheckBox cb_comunicacion;
    public javax.swing.JCheckBox cb_ingles;
    public javax.swing.JCheckBox cb_matematica;
    public javax.swing.JCheckBox cb_psicomotriz;
    public javax.swing.JCheckBox cb_religion1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField jTextFieldApellidoM;
    public javax.swing.JTextField jTextFieldApellidoP;
    public javax.swing.JPasswordField jTextFieldClave;
    public javax.swing.JTextField jTextFieldNumDocumento;
    public javax.swing.JComboBox<String> jTextFieldPregunta1;
    public javax.swing.JComboBox<String> jTextFieldPregunta2;
    public javax.swing.JComboBox<String> jTextFieldPregunta3;
    public javax.swing.JTextField jTextFieldRespuesta1;
    public javax.swing.JTextField jTextFieldRespuesta2;
    public javax.swing.JTextField jTextFieldRespuesta3;
    public javax.swing.JButton jbtnRegistrar;
    public javax.swing.JPasswordField textFieldClave2;
    // End of variables declaration//GEN-END:variables
}
