/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JOptionPane;

/**
 *
 * @author JESSY
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        btnIngresarDire = new javax.swing.JButton();
        btnCambiarClave = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();
        btnIngresarProfe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ingresa tu codigo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 25, 122, -1));

        jLabel2.setText("Ingresa tu contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 65, 122, -1));
        getContentPane().add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 22, 184, -1));

        btnIngresarDire.setText("Ingresar Directivo");
        btnIngresarDire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarDireActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresarDire, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, 35));

        btnCambiarClave.setText("Cambiar contraseña");
        btnCambiarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarClaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnCambiarClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 30));

        jLabel3.setText("¿Se olvidó de su contraseña institucional? ¡recuperelo ahora!");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 176, 338, -1));

        txtClave.setEchoChar('\u25cf');
        txtClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaveActionPerformed(evt);
            }
        });
        getContentPane().add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 62, 184, -1));

        btnIngresarProfe.setText("Ingresar Profesor");
        btnIngresarProfe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarProfeActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresarProfe, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 122, 35));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarDireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarDireActionPerformed
       //Creamos variables Usuario y Contra:)
        String Usuario = "D72549418";
        String Contraseña = "123";
        //Ahora para obtener los valores de txtContrasena
        String Pass = new String(txtClave.getPassword());
        //Creamos las Validaciones
        //lo que se digite en el campo usuario  y campo contrasena es correcto iniciar ir a la siguiente interfaz
        if(txtCod.getText().equals(Usuario)&& Pass.equals(Contraseña)){
                
        ////Siguiente interfaz usando el boton ingresar directivo SI ES CORRECTO EL USUARIO Y CONTRA
        this.setVisible(false);
        MenuDirec menu = new MenuDirec();
        menu.setVisible(true);
        }else{ //y si no pues mensaje de error
            JOptionPane.showMessageDialog(this,"Usuario/Contraseña incorrecta >:)");
        }

        
    }//GEN-LAST:event_btnIngresarDireActionPerformed

    private void btnCambiarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarClaveActionPerformed
       recopilar_codigo_cambioContraseña RcopilarCodigoC = new recopilar_codigo_cambioContraseña();
            RcopilarCodigoC.setVisible(true);
    }//GEN-LAST:event_btnCambiarClaveActionPerformed

    
    
    private void btnIngresarProfeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarProfeActionPerformed
        this.setVisible(false);
        MenuDocente menuDocente= new MenuDocente();
        menuDocente.setVisible(true);
    }//GEN-LAST:event_btnIngresarProfeActionPerformed

    private void txtClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveActionPerformed

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCambiarClave;
    public javax.swing.JButton btnIngresarDire;
    public javax.swing.JButton btnIngresarProfe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JPasswordField txtClave;
    public javax.swing.JTextField txtCod;
    // End of variables declaration//GEN-END:variables
}
