/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author JESSY
 */
public class recuperar_contraseña_preguntas extends javax.swing.JFrame {

    /**
     * Creates new form recuperar_contraseña_preguntas
     */
    public recuperar_contraseña_preguntas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_RecuperarContraseña_PreguntaUno = new javax.swing.JLabel();
        txt_RecuperarContraseña_RespuestaDos = new javax.swing.JTextField();
        txt_RecuperarContraseña_PreguntaDos = new javax.swing.JLabel();
        txt_RecuperarContraseña_RespuestaUno = new javax.swing.JTextField();
        txt_RecuperarContraseña_PreguntaTres = new javax.swing.JLabel();
        txt_RecuperarContraseña_RespuestaTres = new javax.swing.JTextField();
        txt_RecuperarContraseña_PreguntaCuatro = new javax.swing.JLabel();
        txt_RecuperarContraseña_RespuestaCuatro = new javax.swing.JTextField();
        txt_RecuperarContraseña_PreguntaCinco = new javax.swing.JLabel();
        txt_RecuperarContraseña_RespuestaCinco = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_RecuperarContraseña_RepetirContraseña = new javax.swing.JPasswordField();
        txt_RecuperarContraseña_contraseña = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        btn_RecuperarContraseña_Actualizar = new javax.swing.JButton();
        btn_RecuperarContraseña_Cancelar = new javax.swing.JButton();
        btn_RecuperarContraseña_VerContraseña = new javax.swing.JButton();
        btn_RecuperarContraseña_VerRepetirContraseña = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_RecuperarContraseña_PreguntaUno.setText("pregunta 1");
        jPanel1.add(txt_RecuperarContraseña_PreguntaUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, -1));
        jPanel1.add(txt_RecuperarContraseña_RespuestaDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 210, -1));

        txt_RecuperarContraseña_PreguntaDos.setText("pregunta 2");
        jPanel1.add(txt_RecuperarContraseña_PreguntaDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 70, 210, -1));
        jPanel1.add(txt_RecuperarContraseña_RespuestaUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 210, -1));

        txt_RecuperarContraseña_PreguntaTres.setText("pregunta 3");
        jPanel1.add(txt_RecuperarContraseña_PreguntaTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 210, -1));
        jPanel1.add(txt_RecuperarContraseña_RespuestaTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 210, -1));

        txt_RecuperarContraseña_PreguntaCuatro.setText("pregunta 4");
        jPanel1.add(txt_RecuperarContraseña_PreguntaCuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 210, -1));
        jPanel1.add(txt_RecuperarContraseña_RespuestaCuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 210, -1));

        txt_RecuperarContraseña_PreguntaCinco.setText("pregunta 5");
        jPanel1.add(txt_RecuperarContraseña_PreguntaCinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 210, -1));
        jPanel1.add(txt_RecuperarContraseña_RespuestaCinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 210, -1));

        jLabel7.setText("Repita su contraseña:");

        txt_RecuperarContraseña_RepetirContraseña.setEchoChar('\u25cf');

        txt_RecuperarContraseña_contraseña.setEchoChar('\u25cf');

        jLabel6.setText("Ingresa la nueva contraseña:");

        btn_RecuperarContraseña_Actualizar.setText("Actualizar");

        btn_RecuperarContraseña_Cancelar.setText("Cancelar");

        btn_RecuperarContraseña_VerContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RecuperarContraseña_VerContraseñaActionPerformed(evt);
            }
        });

        btn_RecuperarContraseña_VerRepetirContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RecuperarContraseña_VerRepetirContraseñaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(btn_RecuperarContraseña_Actualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_RecuperarContraseña_Cancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_RecuperarContraseña_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_RecuperarContraseña_RepetirContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_RecuperarContraseña_VerContraseña)
                    .addComponent(btn_RecuperarContraseña_VerRepetirContraseña))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_RecuperarContraseña_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_RecuperarContraseña_VerContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_RecuperarContraseña_RepetirContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_RecuperarContraseña_VerRepetirContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btn_RecuperarContraseña_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_RecuperarContraseña_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RecuperarContraseña_VerContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RecuperarContraseña_VerContraseñaActionPerformed

        // Verificar si el campo de contraseña muestra el texto real o no
        if (txt_RecuperarContraseña_contraseña.getEchoChar() == (char) 0) {
            // Cambiar a modo de texto oculto
            txt_RecuperarContraseña_contraseña.setEchoChar('\u25cf');
        } else {
            // Cambiar a modo de texto visible
            txt_RecuperarContraseña_contraseña.setEchoChar((char) 0);
        }
        //-----------------------------------------------------------

    }//GEN-LAST:event_btn_RecuperarContraseña_VerContraseñaActionPerformed

    private void btn_RecuperarContraseña_VerRepetirContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RecuperarContraseña_VerRepetirContraseñaActionPerformed
        
        // Verificar si el campo de contraseña muestra el texto real o no
        if (txt_RecuperarContraseña_RepetirContraseña.getEchoChar() == (char) 0) {
            // Cambiar a modo de texto oculto
            txt_RecuperarContraseña_RepetirContraseña.setEchoChar('\u25cf');
        } else {
            // Cambiar a modo de texto visible
            txt_RecuperarContraseña_RepetirContraseña.setEchoChar((char) 0);
        }
        //-----------------------------------------------------------
    }//GEN-LAST:event_btn_RecuperarContraseña_VerRepetirContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recuperar_contraseña_preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recuperar_contraseña_preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recuperar_contraseña_preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recuperar_contraseña_preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new recuperar_contraseña_preguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_RecuperarContraseña_Actualizar;
    private javax.swing.JButton btn_RecuperarContraseña_Cancelar;
    public javax.swing.JButton btn_RecuperarContraseña_VerContraseña;
    public javax.swing.JButton btn_RecuperarContraseña_VerRepetirContraseña;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txt_RecuperarContraseña_PreguntaCinco;
    private javax.swing.JLabel txt_RecuperarContraseña_PreguntaCuatro;
    private javax.swing.JLabel txt_RecuperarContraseña_PreguntaDos;
    private javax.swing.JLabel txt_RecuperarContraseña_PreguntaTres;
    private javax.swing.JLabel txt_RecuperarContraseña_PreguntaUno;
    private javax.swing.JPasswordField txt_RecuperarContraseña_RepetirContraseña;
    private javax.swing.JTextField txt_RecuperarContraseña_RespuestaCinco;
    private javax.swing.JTextField txt_RecuperarContraseña_RespuestaCuatro;
    private javax.swing.JTextField txt_RecuperarContraseña_RespuestaDos;
    private javax.swing.JTextField txt_RecuperarContraseña_RespuestaTres;
    private javax.swing.JTextField txt_RecuperarContraseña_RespuestaUno;
    private javax.swing.JPasswordField txt_RecuperarContraseña_contraseña;
    // End of variables declaration//GEN-END:variables
}
