/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Asignar;
//import Animacion.Animacion;
import java.awt.Color;
/**
 *
 * @author SARA
 */
public class Principal extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.pnlSlider.setPanelNormal(this.pnlAsignaPortada);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rSLabelTextIcon1 = new RSMaterialComponent.RSLabelTextIcon();
        tab1 = new newscomponents.RSButtonIcon_new();
        tab2 = new newscomponents.RSButtonIcon_new();
        pnlSlider = new newscomponents.RSPanelEffect();
        pnlAsignaPortada = new Vista.Asignar.tabContent3();
        pnlAsignarArea = new Vista.Asignar.tabContent1();
        pnlAsignarTutor = new Vista.Asignar.tabContent2();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(102, 102, 102)));

        rSLabelTextIcon1.setForeground(new java.awt.Color(102, 102, 255));
        rSLabelTextIcon1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSLabelTextIcon1.setText("Asignar");
        rSLabelTextIcon1.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        rSLabelTextIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CREATE_NEW_FOLDER);

        tab1.setBackground(new java.awt.Color(187, 187, 187));
        tab1.setForeground(new java.awt.Color(0, 0, 0));
        tab1.setText("Area");
        tab1.setBackgroundHover(new java.awt.Color(102, 102, 255));
        tab1.setForegroundHover(new java.awt.Color(204, 204, 255));
        tab1.setForegroundIcon(new java.awt.Color(102, 102, 102));
        tab1.setForegroundIconHover(new java.awt.Color(204, 204, 255));
        tab1.setForegroundText(new java.awt.Color(102, 102, 102));
        tab1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FOLDER);
        tab1.setName(""); // NOI18N
        tab1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab1ActionPerformed(evt);
            }
        });

        tab2.setBackground(new java.awt.Color(187, 187, 187));
        tab2.setText("Tutor");
        tab2.setBackgroundHover(new java.awt.Color(102, 102, 255));
        tab2.setForegroundHover(new java.awt.Color(204, 204, 255));
        tab2.setForegroundIcon(new java.awt.Color(102, 102, 102));
        tab2.setForegroundIconHover(new java.awt.Color(204, 204, 255));
        tab2.setForegroundText(new java.awt.Color(102, 102, 102));
        tab2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FOLDER_SHARED);
        tab2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tab1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(266, 266, 266))
        );

        pnlSlider.setBackground(new java.awt.Color(255, 255, 255));
        pnlSlider.setToolTipText("");
        pnlSlider.setName("pnlSlider"); // NOI18N

        pnlAsignaPortada.setName("pnlAsignaPortada"); // NOI18N
        pnlSlider.add(pnlAsignaPortada, "card4");

        pnlAsignarArea.setName("pnlAsignarArea"); // NOI18N
        pnlSlider.add(pnlAsignarArea, "card3");

        pnlAsignarTutor.setName("pnlAsignarTutor"); // NOI18N
        pnlSlider.add(pnlAsignarTutor, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tab2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab2ActionPerformed
        if(this.tab2.isSelected()){
            this.tab2.setSelected(true);
            this.tab1.setSelected(false);
            
            /*this.tab2.setBackground(new Color(102,102,255));        //tab2
            this.tab2.setForeground(new Color(204,204,255));
            this.tab2.setForegroundIcon(new Color(204,204,255));
            this.tab1.setBackground(new Color(255,255,255));        //tab1
            this.tab1.setForeground(new Color(153,153,153));//si no funciona pon setForegroundText
            this.tab1.setForegroundIcon(new Color(102,102,102));*/
        }
        this.pnlSlider.setPanelNormal(this.pnlAsignarTutor);
    }//GEN-LAST:event_tab2ActionPerformed

    private void tab1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab1ActionPerformed
        if(this.tab1.isSelected()){
            this.tab1.setSelected(true);
            this.tab2.setSelected(false);
            //colores
            /*this.tab1.setBackground(new Color(102,102,255));        //tab1
            this.tab1.setForeground(new Color(204,204,255));
            this.tab1.setForegroundIcon(new Color(204,204,255));
            this.tab2.setBackground(new Color(255,255,255));        //tab2
            this.tab2.setForeground(new Color(153,153,153));//si no funciona pon setForegroundText
            this.tab2.setForegroundIcon(new Color(102,102,102));*/
        }
        this.pnlSlider.setPanelNormal(this.pnlAsignarArea);
    }//GEN-LAST:event_tab1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private Vista.Asignar.tabContent3 pnlAsignaPortada;
    private Vista.Asignar.tabContent1 pnlAsignarArea;
    private Vista.Asignar.tabContent2 pnlAsignarTutor;
    private newscomponents.RSPanelEffect pnlSlider;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon1;
    private newscomponents.RSButtonIcon_new tab1;
    private newscomponents.RSButtonIcon_new tab2;
    // End of variables declaration//GEN-END:variables
}
