/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Asignar;

/**
 *
 * @author SARA
 */
public class tabContent2 extends javax.swing.JPanel {

    /**
     * Creates new form tabContent
     */
    public tabContent2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_AsignarArea_registro = new RSMaterialComponent.RSTableMetroCustom();
        rSLabelTextIcon1 = new RSMaterialComponent.RSLabelTextIcon();
        rSTextFieldMaterialIcon1 = new RSMaterialComponent.RSTextFieldMaterialIcon();
        rSButtonIconShadow3 = new RSMaterialComponent.RSButtonIconShadow();
        rSButtonIconShadow2 = new RSMaterialComponent.RSButtonIconShadow();
        rSButtonIconShadow1 = new RSMaterialComponent.RSButtonIconShadow();
        rSDateYear1 = new newscomponents.RSDateYear();
        rSComboBox1 = new RSMaterialComponent.RSComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rSCheckBoxMaterial1 = new RSMaterialComponent.RSCheckBoxMaterial();
        rSCheckBoxMaterial3 = new RSMaterialComponent.RSCheckBoxMaterial();
        rSCheckBoxMaterial4 = new RSMaterialComponent.RSCheckBoxMaterial();
        rSCheckBoxMaterial5 = new RSMaterialComponent.RSCheckBoxMaterial();
        rSCheckBoxMaterial6 = new RSMaterialComponent.RSCheckBoxMaterial();
        rSCheckBoxMaterial7 = new RSMaterialComponent.RSCheckBoxMaterial();
        rSCheckBoxMaterial8 = new RSMaterialComponent.RSCheckBoxMaterial();
        rSCheckBoxMaterial9 = new RSMaterialComponent.RSCheckBoxMaterial();
        rSCheckBoxMaterial10 = new RSMaterialComponent.RSCheckBoxMaterial();
        rSCheckBoxMaterial11 = new RSMaterialComponent.RSCheckBoxMaterial();
        rSCheckBoxMaterial12 = new RSMaterialComponent.RSCheckBoxMaterial();
        rSCheckBoxMaterial13 = new RSMaterialComponent.RSCheckBoxMaterial();
        rSCheckBoxMaterial14 = new RSMaterialComponent.RSCheckBoxMaterial();
        rSCheckBoxMaterial2 = new RSMaterialComponent.RSCheckBoxMaterial();
        rSButtonIconShadow4 = new RSMaterialComponent.RSButtonIconShadow();

        setBackground(new java.awt.Color(255, 255, 255));

        tbl_AsignarArea_registro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Docente", "Grado", "Año"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_AsignarArea_registro.setBackgoundHead(new java.awt.Color(102, 102, 255));
        tbl_AsignarArea_registro.setBackgoundHover(new java.awt.Color(153, 153, 255));
        jScrollPane1.setViewportView(tbl_AsignarArea_registro);

        rSLabelTextIcon1.setForeground(new java.awt.Color(102, 102, 255));
        rSLabelTextIcon1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSLabelTextIcon1.setText("Tutor");
        rSLabelTextIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FOLDER_SHARED);

        rSTextFieldMaterialIcon1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        rSTextFieldMaterialIcon1.setForeground(new java.awt.Color(153, 153, 153));
        rSTextFieldMaterialIcon1.setColorIcon(new java.awt.Color(51, 51, 51));
        rSTextFieldMaterialIcon1.setColorMaterial(new java.awt.Color(153, 153, 153));
        rSTextFieldMaterialIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        rSTextFieldMaterialIcon1.setPlaceholder("Buscar");

        rSButtonIconShadow3.setBackground(new java.awt.Color(255, 102, 102));
        rSButtonIconShadow3.setBackgroundHover(new java.awt.Color(204, 0, 0));
        rSButtonIconShadow3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE_FOREVER);

        rSButtonIconShadow2.setBackground(new java.awt.Color(255, 204, 0));
        rSButtonIconShadow2.setBackgroundHover(new java.awt.Color(153, 102, 0));
        rSButtonIconShadow2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);

        rSButtonIconShadow1.setBackground(new java.awt.Color(0, 102, 204));
        rSButtonIconShadow1.setBackgroundHover(new java.awt.Color(0, 51, 102));
        rSButtonIconShadow1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILTER_LIST);

        rSDateYear1.setColorArrow(new java.awt.Color(153, 153, 255));
        rSDateYear1.setColorBoton(new java.awt.Color(102, 102, 255));
        rSDateYear1.setColorFondo(new java.awt.Color(102, 102, 255));
        rSDateYear1.setColorListaItems(new java.awt.Color(204, 204, 204));
        rSDateYear1.setColorSeleccion(new java.awt.Color(102, 102, 255));

        rSComboBox1.setColorArrow(new java.awt.Color(153, 153, 255));
        rSComboBox1.setColorBorde(new java.awt.Color(58, 66, 225));
        rSComboBox1.setColorBoton(new java.awt.Color(102, 102, 255));
        rSComboBox1.setColorFondo(new java.awt.Color(102, 102, 255));
        rSComboBox1.setColorListaItems(new java.awt.Color(204, 204, 204));
        rSComboBox1.setColorSeleccion(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Año");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Docente");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Inicial: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Primaria:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Secundaria:");

        rSCheckBoxMaterial1.setForeground(new java.awt.Color(0, 51, 102));
        rSCheckBoxMaterial1.setText("1er Nivel");
        rSCheckBoxMaterial1.setColorCheck(new java.awt.Color(102, 102, 255));
        rSCheckBoxMaterial1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        rSCheckBoxMaterial3.setForeground(new java.awt.Color(0, 51, 102));
        rSCheckBoxMaterial3.setText("3er Nivel");
        rSCheckBoxMaterial3.setColorCheck(new java.awt.Color(102, 102, 255));
        rSCheckBoxMaterial3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        rSCheckBoxMaterial4.setForeground(new java.awt.Color(0, 51, 102));
        rSCheckBoxMaterial4.setText("1er Grado");
        rSCheckBoxMaterial4.setColorCheck(new java.awt.Color(102, 102, 255));
        rSCheckBoxMaterial4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        rSCheckBoxMaterial5.setForeground(new java.awt.Color(0, 51, 102));
        rSCheckBoxMaterial5.setText("2do Grado");
        rSCheckBoxMaterial5.setColorCheck(new java.awt.Color(102, 102, 255));
        rSCheckBoxMaterial5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        rSCheckBoxMaterial6.setForeground(new java.awt.Color(0, 51, 102));
        rSCheckBoxMaterial6.setText("3er Grado");
        rSCheckBoxMaterial6.setColorCheck(new java.awt.Color(102, 102, 255));
        rSCheckBoxMaterial6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        rSCheckBoxMaterial7.setForeground(new java.awt.Color(0, 51, 102));
        rSCheckBoxMaterial7.setText("4to Grado");
        rSCheckBoxMaterial7.setColorCheck(new java.awt.Color(102, 102, 255));
        rSCheckBoxMaterial7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        rSCheckBoxMaterial8.setForeground(new java.awt.Color(0, 51, 102));
        rSCheckBoxMaterial8.setText("5to Grado");
        rSCheckBoxMaterial8.setColorCheck(new java.awt.Color(102, 102, 255));
        rSCheckBoxMaterial8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        rSCheckBoxMaterial9.setForeground(new java.awt.Color(0, 51, 102));
        rSCheckBoxMaterial9.setText("6to Grado");
        rSCheckBoxMaterial9.setColorCheck(new java.awt.Color(102, 102, 255));
        rSCheckBoxMaterial9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        rSCheckBoxMaterial10.setForeground(new java.awt.Color(0, 51, 102));
        rSCheckBoxMaterial10.setText("1er Año");
        rSCheckBoxMaterial10.setColorCheck(new java.awt.Color(102, 102, 255));
        rSCheckBoxMaterial10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        rSCheckBoxMaterial11.setForeground(new java.awt.Color(0, 51, 102));
        rSCheckBoxMaterial11.setText("2do Año");
        rSCheckBoxMaterial11.setColorCheck(new java.awt.Color(102, 102, 255));
        rSCheckBoxMaterial11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        rSCheckBoxMaterial12.setForeground(new java.awt.Color(0, 51, 102));
        rSCheckBoxMaterial12.setText("3er Año");
        rSCheckBoxMaterial12.setColorCheck(new java.awt.Color(102, 102, 255));
        rSCheckBoxMaterial12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        rSCheckBoxMaterial13.setForeground(new java.awt.Color(0, 51, 102));
        rSCheckBoxMaterial13.setText("4to Año");
        rSCheckBoxMaterial13.setColorCheck(new java.awt.Color(102, 102, 255));
        rSCheckBoxMaterial13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        rSCheckBoxMaterial14.setForeground(new java.awt.Color(0, 51, 102));
        rSCheckBoxMaterial14.setText("5to Año");
        rSCheckBoxMaterial14.setColorCheck(new java.awt.Color(102, 102, 255));
        rSCheckBoxMaterial14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        rSCheckBoxMaterial2.setForeground(new java.awt.Color(0, 51, 102));
        rSCheckBoxMaterial2.setText("2do Nivel");
        rSCheckBoxMaterial2.setColorCheck(new java.awt.Color(102, 102, 255));
        rSCheckBoxMaterial2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        rSButtonIconShadow4.setBackground(new java.awt.Color(0, 204, 102));
        rSButtonIconShadow4.setBackgroundHover(new java.awt.Color(0, 102, 51));
        rSButtonIconShadow4.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD_CIRCLE_OUTLINE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rSTextFieldMaterialIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(rSDateYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(rSComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rSButtonIconShadow1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(rSCheckBoxMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rSCheckBoxMaterial2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rSCheckBoxMaterial3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rSCheckBoxMaterial9, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(rSCheckBoxMaterial4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rSCheckBoxMaterial6, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rSCheckBoxMaterial5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rSCheckBoxMaterial7, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rSCheckBoxMaterial8, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(rSCheckBoxMaterial10, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rSCheckBoxMaterial11, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rSCheckBoxMaterial12, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rSCheckBoxMaterial13, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rSCheckBoxMaterial14, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(rSButtonIconShadow2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rSButtonIconShadow3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(rSButtonIconShadow4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSTextFieldMaterialIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rSCheckBoxMaterial10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addComponent(rSCheckBoxMaterial11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rSCheckBoxMaterial12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rSCheckBoxMaterial13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rSCheckBoxMaterial14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rSDateYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rSComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rSButtonIconShadow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rSCheckBoxMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rSCheckBoxMaterial4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rSCheckBoxMaterial2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rSCheckBoxMaterial3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rSCheckBoxMaterial5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rSCheckBoxMaterial6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rSCheckBoxMaterial7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rSCheckBoxMaterial8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rSCheckBoxMaterial9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSButtonIconShadow4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonIconShadow2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonIconShadow3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private RSMaterialComponent.RSButtonIconShadow rSButtonIconShadow1;
    private RSMaterialComponent.RSButtonIconShadow rSButtonIconShadow2;
    private RSMaterialComponent.RSButtonIconShadow rSButtonIconShadow3;
    private RSMaterialComponent.RSButtonIconShadow rSButtonIconShadow4;
    private RSMaterialComponent.RSCheckBoxMaterial rSCheckBoxMaterial1;
    private RSMaterialComponent.RSCheckBoxMaterial rSCheckBoxMaterial10;
    private RSMaterialComponent.RSCheckBoxMaterial rSCheckBoxMaterial11;
    private RSMaterialComponent.RSCheckBoxMaterial rSCheckBoxMaterial12;
    private RSMaterialComponent.RSCheckBoxMaterial rSCheckBoxMaterial13;
    private RSMaterialComponent.RSCheckBoxMaterial rSCheckBoxMaterial14;
    private RSMaterialComponent.RSCheckBoxMaterial rSCheckBoxMaterial2;
    private RSMaterialComponent.RSCheckBoxMaterial rSCheckBoxMaterial3;
    private RSMaterialComponent.RSCheckBoxMaterial rSCheckBoxMaterial4;
    private RSMaterialComponent.RSCheckBoxMaterial rSCheckBoxMaterial5;
    private RSMaterialComponent.RSCheckBoxMaterial rSCheckBoxMaterial6;
    private RSMaterialComponent.RSCheckBoxMaterial rSCheckBoxMaterial7;
    private RSMaterialComponent.RSCheckBoxMaterial rSCheckBoxMaterial8;
    private RSMaterialComponent.RSCheckBoxMaterial rSCheckBoxMaterial9;
    private RSMaterialComponent.RSComboBox rSComboBox1;
    private newscomponents.RSDateYear rSDateYear1;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon1;
    private RSMaterialComponent.RSTextFieldMaterialIcon rSTextFieldMaterialIcon1;
    private RSMaterialComponent.RSTableMetroCustom tbl_AsignarArea_registro;
    // End of variables declaration//GEN-END:variables
}
