/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Asignar;

/**
 *
 * @author SARA
 */
public class tabContent2 extends javax.swing.JPanel {

    /**
     * Creates new form tabContent
     */
    public tabContent2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProfes = new RSMaterialComponent.RSTableMetroCustom();
        rSLabelTextIcon1 = new RSMaterialComponent.RSLabelTextIcon();
        txtBuscar = new RSMaterialComponent.RSTextFieldMaterialIcon();
        btnBorrar = new RSMaterialComponent.RSButtonIconShadow();
        btnActualizar = new RSMaterialComponent.RSButtonIconShadow();
        btnLimpiar = new RSMaterialComponent.RSButtonIconShadow();
        cbxTutor = new RSMaterialComponent.RSComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Ini3 = new RSMaterialComponent.RSCheckBoxMaterial();
        Ini5 = new RSMaterialComponent.RSCheckBoxMaterial();
        Pri1 = new RSMaterialComponent.RSCheckBoxMaterial();
        Pri2 = new RSMaterialComponent.RSCheckBoxMaterial();
        Pri3 = new RSMaterialComponent.RSCheckBoxMaterial();
        Pri4 = new RSMaterialComponent.RSCheckBoxMaterial();
        Pri5 = new RSMaterialComponent.RSCheckBoxMaterial();
        Pri6 = new RSMaterialComponent.RSCheckBoxMaterial();
        Sec1 = new RSMaterialComponent.RSCheckBoxMaterial();
        Sec2 = new RSMaterialComponent.RSCheckBoxMaterial();
        Sec3 = new RSMaterialComponent.RSCheckBoxMaterial();
        Sec4 = new RSMaterialComponent.RSCheckBoxMaterial();
        Sec5 = new RSMaterialComponent.RSCheckBoxMaterial();
        Ini4 = new RSMaterialComponent.RSCheckBoxMaterial();
        btnCrear = new RSMaterialComponent.RSButtonIconShadow();
        txtAnio = new RSMaterialComponent.RSTextFieldTwo();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGrados = new RSMaterialComponent.RSTableMetroCustom();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        tblProfes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Año", "Código", "Nombre Docente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblProfes.setBackgoundHead(new java.awt.Color(102, 102, 255));
        tblProfes.setBackgoundHover(new java.awt.Color(153, 153, 255));
        tblProfes.setName("tblProfes"); // NOI18N
        jScrollPane1.setViewportView(tblProfes);
        if (tblProfes.getColumnModel().getColumnCount() > 0) {
            tblProfes.getColumnModel().getColumn(0).setPreferredWidth(20);
            tblProfes.getColumnModel().getColumn(1).setPreferredWidth(50);
            tblProfes.getColumnModel().getColumn(1).setHeaderValue("Código");
            tblProfes.getColumnModel().getColumn(2).setPreferredWidth(500);
            tblProfes.getColumnModel().getColumn(2).setHeaderValue("Nombre Docente");
        }

        rSLabelTextIcon1.setForeground(new java.awt.Color(102, 102, 255));
        rSLabelTextIcon1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSLabelTextIcon1.setText("Tutor");
        rSLabelTextIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FOLDER_SHARED);

        txtBuscar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtBuscar.setForeground(new java.awt.Color(153, 153, 153));
        txtBuscar.setColorIcon(new java.awt.Color(51, 51, 51));
        txtBuscar.setColorMaterial(new java.awt.Color(153, 153, 153));
        txtBuscar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        txtBuscar.setName("txtBuscar"); // NOI18N
        txtBuscar.setPlaceholder("Buscar");

        btnBorrar.setBackground(new java.awt.Color(255, 102, 102));
        btnBorrar.setBackgroundHover(new java.awt.Color(204, 0, 0));
        btnBorrar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE_FOREVER);
        btnBorrar.setName("btnBorrar"); // NOI18N

        btnActualizar.setBackground(new java.awt.Color(255, 204, 0));
        btnActualizar.setBackgroundHover(new java.awt.Color(153, 102, 0));
        btnActualizar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);
        btnActualizar.setName("btnActualizar"); // NOI18N

        btnLimpiar.setBackground(new java.awt.Color(0, 204, 255));
        btnLimpiar.setBackgroundHover(new java.awt.Color(0, 102, 153));
        btnLimpiar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE_SWEEP);
        btnLimpiar.setName("btnLimpiar"); // NOI18N

        cbxTutor.setColorArrow(new java.awt.Color(153, 153, 255));
        cbxTutor.setColorBorde(new java.awt.Color(58, 66, 225));
        cbxTutor.setColorBoton(new java.awt.Color(102, 102, 255));
        cbxTutor.setColorFondo(new java.awt.Color(102, 102, 255));
        cbxTutor.setColorListaItems(new java.awt.Color(204, 204, 204));
        cbxTutor.setColorSeleccion(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Año");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Tutor");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Inicial: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Primaria:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Secundaria:");

        Ini3.setForeground(new java.awt.Color(0, 51, 102));
        Ini3.setText("3 Añitos");
        Ini3.setColorCheck(new java.awt.Color(102, 102, 255));
        Ini3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Ini3.setName("Ini3"); // NOI18N

        Ini5.setForeground(new java.awt.Color(0, 51, 102));
        Ini5.setText("5 Añitos");
        Ini5.setColorCheck(new java.awt.Color(102, 102, 255));
        Ini5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Ini5.setName("Ini5"); // NOI18N

        Pri1.setForeground(new java.awt.Color(0, 51, 102));
        Pri1.setText("1er Grado");
        Pri1.setColorCheck(new java.awt.Color(102, 102, 255));
        Pri1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Pri1.setName("Pri1"); // NOI18N

        Pri2.setForeground(new java.awt.Color(0, 51, 102));
        Pri2.setText("2do Grado");
        Pri2.setColorCheck(new java.awt.Color(102, 102, 255));
        Pri2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Pri2.setName("Pri2"); // NOI18N

        Pri3.setForeground(new java.awt.Color(0, 51, 102));
        Pri3.setText("3er Grado");
        Pri3.setColorCheck(new java.awt.Color(102, 102, 255));
        Pri3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Pri3.setName("Pri3"); // NOI18N

        Pri4.setForeground(new java.awt.Color(0, 51, 102));
        Pri4.setText("4to Grado");
        Pri4.setColorCheck(new java.awt.Color(102, 102, 255));
        Pri4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Pri4.setName("Pri4"); // NOI18N

        Pri5.setForeground(new java.awt.Color(0, 51, 102));
        Pri5.setText("5to Grado");
        Pri5.setColorCheck(new java.awt.Color(102, 102, 255));
        Pri5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Pri5.setName("Pri5"); // NOI18N

        Pri6.setForeground(new java.awt.Color(0, 51, 102));
        Pri6.setText("6to Grado");
        Pri6.setColorCheck(new java.awt.Color(102, 102, 255));
        Pri6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Pri6.setName("Pri6"); // NOI18N

        Sec1.setForeground(new java.awt.Color(0, 51, 102));
        Sec1.setText("1er Año");
        Sec1.setColorCheck(new java.awt.Color(102, 102, 255));
        Sec1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Sec1.setName("Sec1"); // NOI18N

        Sec2.setForeground(new java.awt.Color(0, 51, 102));
        Sec2.setText("2do Año");
        Sec2.setColorCheck(new java.awt.Color(102, 102, 255));
        Sec2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Sec2.setName("Sec2"); // NOI18N

        Sec3.setForeground(new java.awt.Color(0, 51, 102));
        Sec3.setText("3er Año");
        Sec3.setColorCheck(new java.awt.Color(102, 102, 255));
        Sec3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Sec3.setName("Sec3"); // NOI18N

        Sec4.setForeground(new java.awt.Color(0, 51, 102));
        Sec4.setText("4to Año");
        Sec4.setColorCheck(new java.awt.Color(102, 102, 255));
        Sec4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Sec4.setName("Sec4"); // NOI18N

        Sec5.setForeground(new java.awt.Color(0, 51, 102));
        Sec5.setText("5to Año");
        Sec5.setColorCheck(new java.awt.Color(102, 102, 255));
        Sec5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Sec5.setName("Sec5"); // NOI18N

        Ini4.setForeground(new java.awt.Color(0, 51, 102));
        Ini4.setText("4 Añitos");
        Ini4.setColorCheck(new java.awt.Color(102, 102, 255));
        Ini4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Ini4.setName("Ini4"); // NOI18N

        btnCrear.setBackground(new java.awt.Color(0, 204, 102));
        btnCrear.setBackgroundHover(new java.awt.Color(0, 102, 51));
        btnCrear.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD_CIRCLE_OUTLINE);
        btnCrear.setName("btnCrear"); // NOI18N

        txtAnio.setForeground(new java.awt.Color(0, 51, 102));
        txtAnio.setBorderColor(new java.awt.Color(0, 51, 102));
        txtAnio.setName("txtAnio"); // NOI18N
        txtAnio.setPhColor(new java.awt.Color(102, 102, 102));
        txtAnio.setPlaceholder("Año");

        tblGrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Grado"
            }
        ));
        tblGrados.setBackgoundHead(new java.awt.Color(102, 102, 255));
        tblGrados.setBackgoundHover(new java.awt.Color(153, 153, 255));
        tblGrados.setName("tblGrados"); // NOI18N
        jScrollPane2.setViewportView(tblGrados);
        if (tblGrados.getColumnModel().getColumnCount() > 0) {
            tblGrados.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Profesores Encargados");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Grados Asignados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(Ini3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ini4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ini5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pri6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Pri1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Pri3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Pri2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Pri4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Pri5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Sec4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sec5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(Sec1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sec2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sec3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtAnio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxTutor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(155, 155, 155)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 349, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(92, 92, 92)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbxTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Ini3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Pri1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Ini4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Ini5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Pri2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Pri3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Pri4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Pri5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addGap(57, 57, 57)
                                                    .addComponent(Sec2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(Sec3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(Sec4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(Sec5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel7))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(Sec1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Pri6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public RSMaterialComponent.RSCheckBoxMaterial Ini3;
    public RSMaterialComponent.RSCheckBoxMaterial Ini4;
    public RSMaterialComponent.RSCheckBoxMaterial Ini5;
    public RSMaterialComponent.RSCheckBoxMaterial Pri1;
    public RSMaterialComponent.RSCheckBoxMaterial Pri2;
    public RSMaterialComponent.RSCheckBoxMaterial Pri3;
    public RSMaterialComponent.RSCheckBoxMaterial Pri4;
    public RSMaterialComponent.RSCheckBoxMaterial Pri5;
    public RSMaterialComponent.RSCheckBoxMaterial Pri6;
    public RSMaterialComponent.RSCheckBoxMaterial Sec1;
    public RSMaterialComponent.RSCheckBoxMaterial Sec2;
    public RSMaterialComponent.RSCheckBoxMaterial Sec3;
    public RSMaterialComponent.RSCheckBoxMaterial Sec4;
    public RSMaterialComponent.RSCheckBoxMaterial Sec5;
    public RSMaterialComponent.RSButtonIconShadow btnActualizar;
    public RSMaterialComponent.RSButtonIconShadow btnBorrar;
    public RSMaterialComponent.RSButtonIconShadow btnCrear;
    public RSMaterialComponent.RSButtonIconShadow btnLimpiar;
    public RSMaterialComponent.RSComboBox cbxTutor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon1;
    public RSMaterialComponent.RSTableMetroCustom tblGrados;
    public RSMaterialComponent.RSTableMetroCustom tblProfes;
    public RSMaterialComponent.RSTextFieldTwo txtAnio;
    public RSMaterialComponent.RSTextFieldMaterialIcon txtBuscar;
    // End of variables declaration//GEN-END:variables
}
