/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Asignar;

/**
 *
 * @author SARA
 */
public class tabContent1 extends javax.swing.JPanel {

    /**
     * Creates new form tabContent
     */
    public tabContent1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_AsignarArea_registro = new RSMaterialComponent.RSTableMetroCustom();
        rSLabelTextIcon1 = new RSMaterialComponent.RSLabelTextIcon();
        jtxtBuscar = new RSMaterialComponent.RSTextFieldMaterialIcon();
        btn_AsignarArea_borrar = new RSMaterialComponent.RSButtonIconShadow();
        btn_AsignarArea_actualizar = new RSMaterialComponent.RSButtonIconShadow();
        jbtnFiltrar = new RSMaterialComponent.RSButtonIconShadow();
        cb_AsignarArea_areas = new RSMaterialComponent.RSComboBox();
        cb_AsignarArea_docente = new RSMaterialComponent.RSComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ckb_AsignarArea_TresAñitos = new RSMaterialComponent.RSCheckBoxMaterial();
        ckb_AsignarArea_CincoAñitos = new RSMaterialComponent.RSCheckBoxMaterial();
        ckb_AsignarArea_UnoPrimaria = new RSMaterialComponent.RSCheckBoxMaterial();
        ckb_AsignarArea_DosPrimaria = new RSMaterialComponent.RSCheckBoxMaterial();
        ckb_AsignarArea_TresPrimaria = new RSMaterialComponent.RSCheckBoxMaterial();
        ckb_AsignarArea_CuatroPrimaria = new RSMaterialComponent.RSCheckBoxMaterial();
        ckb_AsignarArea_CincoPrimaria = new RSMaterialComponent.RSCheckBoxMaterial();
        ckb_AsignarArea_SeisPrimaria = new RSMaterialComponent.RSCheckBoxMaterial();
        ckb_AsignarArea_UnoSecundaria = new RSMaterialComponent.RSCheckBoxMaterial();
        ckb_AsignarArea_DosSecundaria = new RSMaterialComponent.RSCheckBoxMaterial();
        ckb_AsignarArea_TresSecundaria = new RSMaterialComponent.RSCheckBoxMaterial();
        ckb_AsignarArea_CuatroSecundaria = new RSMaterialComponent.RSCheckBoxMaterial();
        ckb_AsignarArea_CincoSecundaria = new RSMaterialComponent.RSCheckBoxMaterial();
        ckb_AsignarArea_CuatroAñitos = new RSMaterialComponent.RSCheckBoxMaterial();
        btn_AsignarArea_crear = new RSMaterialComponent.RSButtonIconShadow();
        txt_AsignarAreaDirectivo_año = new RSMaterialComponent.RSTextFieldTwo();

        setBackground(new java.awt.Color(255, 255, 255));

        tbl_AsignarArea_registro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Docente", "Area", "Grado", "Año"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_AsignarArea_registro.setBackgoundHead(new java.awt.Color(102, 102, 255));
        tbl_AsignarArea_registro.setBackgoundHover(new java.awt.Color(153, 153, 255));
        tbl_AsignarArea_registro.setName("tbl_AsignarArea_registro"); // NOI18N
        jScrollPane1.setViewportView(tbl_AsignarArea_registro);

        rSLabelTextIcon1.setForeground(new java.awt.Color(102, 102, 255));
        rSLabelTextIcon1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSLabelTextIcon1.setText("Area");
        rSLabelTextIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FOLDER);

        jtxtBuscar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jtxtBuscar.setForeground(new java.awt.Color(153, 153, 153));
        jtxtBuscar.setColorIcon(new java.awt.Color(51, 51, 51));
        jtxtBuscar.setColorMaterial(new java.awt.Color(153, 153, 153));
        jtxtBuscar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        jtxtBuscar.setName("jtxtBuscar"); // NOI18N
        jtxtBuscar.setPlaceholder("Buscar");

        btn_AsignarArea_borrar.setBackground(new java.awt.Color(255, 102, 102));
        btn_AsignarArea_borrar.setBackgroundHover(new java.awt.Color(204, 0, 0));
        btn_AsignarArea_borrar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE_FOREVER);
        btn_AsignarArea_borrar.setName("btn_AsignarArea_borrar"); // NOI18N

        btn_AsignarArea_actualizar.setBackground(new java.awt.Color(255, 204, 0));
        btn_AsignarArea_actualizar.setBackgroundHover(new java.awt.Color(153, 102, 0));
        btn_AsignarArea_actualizar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);
        btn_AsignarArea_actualizar.setName("btn_AsignarArea_actualizar"); // NOI18N

        jbtnFiltrar.setBackground(new java.awt.Color(0, 102, 204));
        jbtnFiltrar.setBackgroundHover(new java.awt.Color(0, 51, 102));
        jbtnFiltrar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILTER_LIST);

        cb_AsignarArea_areas.setColorArrow(new java.awt.Color(153, 153, 255));
        cb_AsignarArea_areas.setColorBorde(new java.awt.Color(58, 66, 225));
        cb_AsignarArea_areas.setColorBoton(new java.awt.Color(102, 102, 255));
        cb_AsignarArea_areas.setColorFondo(new java.awt.Color(102, 102, 255));
        cb_AsignarArea_areas.setColorListaItems(new java.awt.Color(204, 204, 204));
        cb_AsignarArea_areas.setColorSeleccion(new java.awt.Color(102, 102, 255));
        cb_AsignarArea_areas.setName("cb_AsignarArea_areas"); // NOI18N

        cb_AsignarArea_docente.setColorArrow(new java.awt.Color(153, 153, 255));
        cb_AsignarArea_docente.setColorBorde(new java.awt.Color(58, 66, 225));
        cb_AsignarArea_docente.setColorBoton(new java.awt.Color(102, 102, 255));
        cb_AsignarArea_docente.setColorFondo(new java.awt.Color(102, 102, 255));
        cb_AsignarArea_docente.setColorListaItems(new java.awt.Color(204, 204, 204));
        cb_AsignarArea_docente.setColorSeleccion(new java.awt.Color(102, 102, 255));
        cb_AsignarArea_docente.setName("cb_AsignarArea_docente"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Año");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Area");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Docente");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Inicial: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Primaria:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Secundaria:");

        ckb_AsignarArea_TresAñitos.setForeground(new java.awt.Color(0, 51, 102));
        ckb_AsignarArea_TresAñitos.setText("3 Añitos");
        ckb_AsignarArea_TresAñitos.setColorCheck(new java.awt.Color(102, 102, 255));
        ckb_AsignarArea_TresAñitos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ckb_AsignarArea_TresAñitos.setName("ckb_AsignarArea_TresAñitos"); // NOI18N
        ckb_AsignarArea_TresAñitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckb_AsignarArea_TresAñitosActionPerformed(evt);
            }
        });

        ckb_AsignarArea_CincoAñitos.setForeground(new java.awt.Color(0, 51, 102));
        ckb_AsignarArea_CincoAñitos.setText("5 Añitos");
        ckb_AsignarArea_CincoAñitos.setColorCheck(new java.awt.Color(102, 102, 255));
        ckb_AsignarArea_CincoAñitos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ckb_AsignarArea_CincoAñitos.setName("ckb_AsignarArea_CincoAñitos"); // NOI18N

        ckb_AsignarArea_UnoPrimaria.setForeground(new java.awt.Color(0, 51, 102));
        ckb_AsignarArea_UnoPrimaria.setText("1er Grado");
        ckb_AsignarArea_UnoPrimaria.setColorCheck(new java.awt.Color(102, 102, 255));
        ckb_AsignarArea_UnoPrimaria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ckb_AsignarArea_UnoPrimaria.setName("ckb_AsignarArea_UnoPrimaria"); // NOI18N

        ckb_AsignarArea_DosPrimaria.setForeground(new java.awt.Color(0, 51, 102));
        ckb_AsignarArea_DosPrimaria.setText("2do Grado");
        ckb_AsignarArea_DosPrimaria.setColorCheck(new java.awt.Color(102, 102, 255));
        ckb_AsignarArea_DosPrimaria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        ckb_AsignarArea_TresPrimaria.setForeground(new java.awt.Color(0, 51, 102));
        ckb_AsignarArea_TresPrimaria.setText("3er Grado");
        ckb_AsignarArea_TresPrimaria.setColorCheck(new java.awt.Color(102, 102, 255));
        ckb_AsignarArea_TresPrimaria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ckb_AsignarArea_TresPrimaria.setName("ckb_AsignarArea_TresPrimaria"); // NOI18N

        ckb_AsignarArea_CuatroPrimaria.setForeground(new java.awt.Color(0, 51, 102));
        ckb_AsignarArea_CuatroPrimaria.setText("4to Grado");
        ckb_AsignarArea_CuatroPrimaria.setColorCheck(new java.awt.Color(102, 102, 255));
        ckb_AsignarArea_CuatroPrimaria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ckb_AsignarArea_CuatroPrimaria.setName("ckb_AsignarArea_CuatroPrimaria"); // NOI18N

        ckb_AsignarArea_CincoPrimaria.setForeground(new java.awt.Color(0, 51, 102));
        ckb_AsignarArea_CincoPrimaria.setText("5to Grado");
        ckb_AsignarArea_CincoPrimaria.setColorCheck(new java.awt.Color(102, 102, 255));
        ckb_AsignarArea_CincoPrimaria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ckb_AsignarArea_CincoPrimaria.setName("ckb_AsignarArea_CincoPrimaria"); // NOI18N

        ckb_AsignarArea_SeisPrimaria.setForeground(new java.awt.Color(0, 51, 102));
        ckb_AsignarArea_SeisPrimaria.setText("6to Grado");
        ckb_AsignarArea_SeisPrimaria.setColorCheck(new java.awt.Color(102, 102, 255));
        ckb_AsignarArea_SeisPrimaria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ckb_AsignarArea_SeisPrimaria.setName("ckb_AsignarArea_SeisPrimaria"); // NOI18N

        ckb_AsignarArea_UnoSecundaria.setForeground(new java.awt.Color(0, 51, 102));
        ckb_AsignarArea_UnoSecundaria.setText("1er Año");
        ckb_AsignarArea_UnoSecundaria.setColorCheck(new java.awt.Color(102, 102, 255));
        ckb_AsignarArea_UnoSecundaria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ckb_AsignarArea_UnoSecundaria.setName("ckb_AsignarArea_UnoSecundaria"); // NOI18N

        ckb_AsignarArea_DosSecundaria.setForeground(new java.awt.Color(0, 51, 102));
        ckb_AsignarArea_DosSecundaria.setText("2do Año");
        ckb_AsignarArea_DosSecundaria.setColorCheck(new java.awt.Color(102, 102, 255));
        ckb_AsignarArea_DosSecundaria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ckb_AsignarArea_DosSecundaria.setName("ckb_AsignarArea_DosSecundaria"); // NOI18N

        ckb_AsignarArea_TresSecundaria.setForeground(new java.awt.Color(0, 51, 102));
        ckb_AsignarArea_TresSecundaria.setText("3er Año");
        ckb_AsignarArea_TresSecundaria.setColorCheck(new java.awt.Color(102, 102, 255));
        ckb_AsignarArea_TresSecundaria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ckb_AsignarArea_TresSecundaria.setName("ckb_AsignarArea_TresSecundaria"); // NOI18N

        ckb_AsignarArea_CuatroSecundaria.setForeground(new java.awt.Color(0, 51, 102));
        ckb_AsignarArea_CuatroSecundaria.setText("4to Año");
        ckb_AsignarArea_CuatroSecundaria.setColorCheck(new java.awt.Color(102, 102, 255));
        ckb_AsignarArea_CuatroSecundaria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ckb_AsignarArea_CuatroSecundaria.setName("ckb_AsignarArea_CuatroSecundaria"); // NOI18N

        ckb_AsignarArea_CincoSecundaria.setForeground(new java.awt.Color(0, 51, 102));
        ckb_AsignarArea_CincoSecundaria.setText("5to Año");
        ckb_AsignarArea_CincoSecundaria.setColorCheck(new java.awt.Color(102, 102, 255));
        ckb_AsignarArea_CincoSecundaria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ckb_AsignarArea_CincoSecundaria.setName("ckb_AsignarArea_CincoSecundaria"); // NOI18N

        ckb_AsignarArea_CuatroAñitos.setForeground(new java.awt.Color(0, 51, 102));
        ckb_AsignarArea_CuatroAñitos.setText("4 Añitos");
        ckb_AsignarArea_CuatroAñitos.setColorCheck(new java.awt.Color(102, 102, 255));
        ckb_AsignarArea_CuatroAñitos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ckb_AsignarArea_CuatroAñitos.setName("ckb_AsignarArea_CuatroAñitos"); // NOI18N

        btn_AsignarArea_crear.setBackground(new java.awt.Color(0, 204, 102));
        btn_AsignarArea_crear.setBackgroundHover(new java.awt.Color(0, 102, 51));
        btn_AsignarArea_crear.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD_CIRCLE_OUTLINE);
        btn_AsignarArea_crear.setName("btn_AsignarArea_crear"); // NOI18N

        txt_AsignarAreaDirectivo_año.setForeground(new java.awt.Color(0, 51, 102));
        txt_AsignarAreaDirectivo_año.setBorderColor(new java.awt.Color(0, 51, 102));
        txt_AsignarAreaDirectivo_año.setName("txt_AsignarAreaDirectivo_año"); // NOI18N
        txt_AsignarAreaDirectivo_año.setPhColor(new java.awt.Color(102, 102, 102));
        txt_AsignarAreaDirectivo_año.setPlaceholder("Año");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(cb_AsignarArea_docente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(cb_AsignarArea_areas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnFiltrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_AsignarAreaDirectivo_año, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btn_AsignarArea_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_AsignarArea_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btn_AsignarArea_crear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(115, 115, 115))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(ckb_AsignarArea_TresAñitos, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ckb_AsignarArea_CuatroAñitos, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ckb_AsignarArea_CincoAñitos, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ckb_AsignarArea_SeisPrimaria, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(ckb_AsignarArea_UnoPrimaria, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ckb_AsignarArea_TresPrimaria, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ckb_AsignarArea_DosPrimaria, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ckb_AsignarArea_CuatroPrimaria, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ckb_AsignarArea_CincoPrimaria, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(ckb_AsignarArea_UnoSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ckb_AsignarArea_DosSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ckb_AsignarArea_TresSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ckb_AsignarArea_CuatroSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ckb_AsignarArea_CincoSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_AsignarArea_crear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_AsignarArea_actualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_AsignarArea_borrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ckb_AsignarArea_UnoSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(57, 57, 57)
                                    .addComponent(ckb_AsignarArea_DosSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ckb_AsignarArea_TresSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ckb_AsignarArea_CuatroSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ckb_AsignarArea_CincoSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ckb_AsignarArea_TresAñitos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ckb_AsignarArea_UnoPrimaria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ckb_AsignarArea_CuatroAñitos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ckb_AsignarArea_CincoAñitos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ckb_AsignarArea_DosPrimaria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ckb_AsignarArea_TresPrimaria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ckb_AsignarArea_CuatroPrimaria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ckb_AsignarArea_CincoPrimaria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ckb_AsignarArea_SeisPrimaria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_AsignarAreaDirectivo_año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_AsignarArea_areas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_AsignarArea_docente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ckb_AsignarArea_TresAñitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckb_AsignarArea_TresAñitosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckb_AsignarArea_TresAñitosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public RSMaterialComponent.RSButtonIconShadow btn_AsignarArea_actualizar;
    public RSMaterialComponent.RSButtonIconShadow btn_AsignarArea_borrar;
    public RSMaterialComponent.RSButtonIconShadow btn_AsignarArea_crear;
    public RSMaterialComponent.RSComboBox cb_AsignarArea_areas;
    public RSMaterialComponent.RSComboBox cb_AsignarArea_docente;
    public RSMaterialComponent.RSCheckBoxMaterial ckb_AsignarArea_CincoAñitos;
    public RSMaterialComponent.RSCheckBoxMaterial ckb_AsignarArea_CincoPrimaria;
    public RSMaterialComponent.RSCheckBoxMaterial ckb_AsignarArea_CincoSecundaria;
    public RSMaterialComponent.RSCheckBoxMaterial ckb_AsignarArea_CuatroAñitos;
    public RSMaterialComponent.RSCheckBoxMaterial ckb_AsignarArea_CuatroPrimaria;
    public RSMaterialComponent.RSCheckBoxMaterial ckb_AsignarArea_CuatroSecundaria;
    public RSMaterialComponent.RSCheckBoxMaterial ckb_AsignarArea_DosPrimaria;
    public RSMaterialComponent.RSCheckBoxMaterial ckb_AsignarArea_DosSecundaria;
    public RSMaterialComponent.RSCheckBoxMaterial ckb_AsignarArea_SeisPrimaria;
    public RSMaterialComponent.RSCheckBoxMaterial ckb_AsignarArea_TresAñitos;
    public RSMaterialComponent.RSCheckBoxMaterial ckb_AsignarArea_TresPrimaria;
    public RSMaterialComponent.RSCheckBoxMaterial ckb_AsignarArea_TresSecundaria;
    public RSMaterialComponent.RSCheckBoxMaterial ckb_AsignarArea_UnoPrimaria;
    public RSMaterialComponent.RSCheckBoxMaterial ckb_AsignarArea_UnoSecundaria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    public RSMaterialComponent.RSButtonIconShadow jbtnFiltrar;
    public RSMaterialComponent.RSTextFieldMaterialIcon jtxtBuscar;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon1;
    public RSMaterialComponent.RSTableMetroCustom tbl_AsignarArea_registro;
    public RSMaterialComponent.RSTextFieldTwo txt_AsignarAreaDirectivo_año;
    // End of variables declaration//GEN-END:variables
}
